package co.id.fifgroup.personneladmin.domain;

import java.io.Serializable;
import java.util.Date;

import co.id.fifgroup.core.audit.Traversable;

public class Communication implements Serializable, Traversable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.COMMUNICATION_ID
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private Long communicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.PERSON_ID
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.COMPANY_ID
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.COMM_INFORMATION
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private String commInformation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.COMM_TYPE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private String commType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.START_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.END_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.CREATED_BY
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.CREATION_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_COMMUNICATIONS.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PEA_COMMUNICATIONS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.COMMUNICATION_ID
     *
     * @return the value of PEA_COMMUNICATIONS.COMMUNICATION_ID
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public Long getCommunicationId() {
        return communicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.COMMUNICATION_ID
     *
     * @param communicationId the value for PEA_COMMUNICATIONS.COMMUNICATION_ID
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setCommunicationId(Long communicationId) {
        this.communicationId = communicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.PERSON_ID
     *
     * @return the value of PEA_COMMUNICATIONS.PERSON_ID
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.PERSON_ID
     *
     * @param personId the value for PEA_COMMUNICATIONS.PERSON_ID
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.COMPANY_ID
     *
     * @return the value of PEA_COMMUNICATIONS.COMPANY_ID
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.COMPANY_ID
     *
     * @param companyId the value for PEA_COMMUNICATIONS.COMPANY_ID
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.COMM_INFORMATION
     *
     * @return the value of PEA_COMMUNICATIONS.COMM_INFORMATION
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public String getCommInformation() {
        return commInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.COMM_INFORMATION
     *
     * @param commInformation the value for PEA_COMMUNICATIONS.COMM_INFORMATION
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setCommInformation(String commInformation) {
        this.commInformation = commInformation == null ? null : commInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.COMM_TYPE
     *
     * @return the value of PEA_COMMUNICATIONS.COMM_TYPE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public String getCommType() {
        return commType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.COMM_TYPE
     *
     * @param commType the value for PEA_COMMUNICATIONS.COMM_TYPE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setCommType(String commType) {
        this.commType = commType == null ? null : commType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.START_DATE
     *
     * @return the value of PEA_COMMUNICATIONS.START_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.START_DATE
     *
     * @param startDate the value for PEA_COMMUNICATIONS.START_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.END_DATE
     *
     * @return the value of PEA_COMMUNICATIONS.END_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.END_DATE
     *
     * @param endDate the value for PEA_COMMUNICATIONS.END_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.CREATED_BY
     *
     * @return the value of PEA_COMMUNICATIONS.CREATED_BY
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.CREATED_BY
     *
     * @param createdBy the value for PEA_COMMUNICATIONS.CREATED_BY
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.CREATION_DATE
     *
     * @return the value of PEA_COMMUNICATIONS.CREATION_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.CREATION_DATE
     *
     * @param creationDate the value for PEA_COMMUNICATIONS.CREATION_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.LAST_UPDATED_BY
     *
     * @return the value of PEA_COMMUNICATIONS.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for PEA_COMMUNICATIONS.LAST_UPDATED_BY
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_COMMUNICATIONS.LAST_UPDATE_DATE
     *
     * @return the value of PEA_COMMUNICATIONS.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_COMMUNICATIONS.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for PEA_COMMUNICATIONS.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

	@Override
	public Object getId() {
		return this.communicationId;
	}
}