package co.id.fifgroup.personneladmin.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PrimaryAssignmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public PrimaryAssignmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAssignmentIdIsNull() {
            addCriterion("ASSIGNMENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdIsNotNull() {
            addCriterion("ASSIGNMENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdEqualTo(Long value) {
            addCriterion("ASSIGNMENT_ID =", value, "assignmentId");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdNotEqualTo(Long value) {
            addCriterion("ASSIGNMENT_ID <>", value, "assignmentId");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdGreaterThan(Long value) {
            addCriterion("ASSIGNMENT_ID >", value, "assignmentId");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ASSIGNMENT_ID >=", value, "assignmentId");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdLessThan(Long value) {
            addCriterion("ASSIGNMENT_ID <", value, "assignmentId");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdLessThanOrEqualTo(Long value) {
            addCriterion("ASSIGNMENT_ID <=", value, "assignmentId");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdIn(List<Long> values) {
            addCriterion("ASSIGNMENT_ID in", values, "assignmentId");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdNotIn(List<Long> values) {
            addCriterion("ASSIGNMENT_ID not in", values, "assignmentId");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdBetween(Long value1, Long value2) {
            addCriterion("ASSIGNMENT_ID between", value1, value2, "assignmentId");
            return (Criteria) this;
        }

        public Criteria andAssignmentIdNotBetween(Long value1, Long value2) {
            addCriterion("ASSIGNMENT_ID not between", value1, value2, "assignmentId");
            return (Criteria) this;
        }

        public Criteria andPersonIdIsNull() {
            addCriterion("PERSON_ID is null");
            return (Criteria) this;
        }

        public Criteria andPersonIdIsNotNull() {
            addCriterion("PERSON_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPersonIdEqualTo(Long value) {
            addCriterion("PERSON_ID =", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotEqualTo(Long value) {
            addCriterion("PERSON_ID <>", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdGreaterThan(Long value) {
            addCriterion("PERSON_ID >", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PERSON_ID >=", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdLessThan(Long value) {
            addCriterion("PERSON_ID <", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdLessThanOrEqualTo(Long value) {
            addCriterion("PERSON_ID <=", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdIn(List<Long> values) {
            addCriterion("PERSON_ID in", values, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotIn(List<Long> values) {
            addCriterion("PERSON_ID not in", values, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdBetween(Long value1, Long value2) {
            addCriterion("PERSON_ID between", value1, value2, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotBetween(Long value1, Long value2) {
            addCriterion("PERSON_ID not between", value1, value2, "personId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("COMPANY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("COMPANY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Long value) {
            addCriterion("COMPANY_ID =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Long value) {
            addCriterion("COMPANY_ID <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Long value) {
            addCriterion("COMPANY_ID >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("COMPANY_ID >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Long value) {
            addCriterion("COMPANY_ID <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("COMPANY_ID <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Long> values) {
            addCriterion("COMPANY_ID in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Long> values) {
            addCriterion("COMPANY_ID not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Long value1, Long value2) {
            addCriterion("COMPANY_ID between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("COMPANY_ID not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdIsNull() {
            addCriterion("ORGANIZATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdIsNotNull() {
            addCriterion("ORGANIZATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdEqualTo(Long value) {
            addCriterion("ORGANIZATION_ID =", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdNotEqualTo(Long value) {
            addCriterion("ORGANIZATION_ID <>", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdGreaterThan(Long value) {
            addCriterion("ORGANIZATION_ID >", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ORGANIZATION_ID >=", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdLessThan(Long value) {
            addCriterion("ORGANIZATION_ID <", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdLessThanOrEqualTo(Long value) {
            addCriterion("ORGANIZATION_ID <=", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdIn(List<Long> values) {
            addCriterion("ORGANIZATION_ID in", values, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdNotIn(List<Long> values) {
            addCriterion("ORGANIZATION_ID not in", values, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdBetween(Long value1, Long value2) {
            addCriterion("ORGANIZATION_ID between", value1, value2, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdNotBetween(Long value1, Long value2) {
            addCriterion("ORGANIZATION_ID not between", value1, value2, "organizationId");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNull() {
            addCriterion("JOB_ID is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("JOB_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(Long value) {
            addCriterion("JOB_ID =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(Long value) {
            addCriterion("JOB_ID <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(Long value) {
            addCriterion("JOB_ID >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(Long value) {
            addCriterion("JOB_ID >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(Long value) {
            addCriterion("JOB_ID <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(Long value) {
            addCriterion("JOB_ID <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<Long> values) {
            addCriterion("JOB_ID in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<Long> values) {
            addCriterion("JOB_ID not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(Long value1, Long value2) {
            addCriterion("JOB_ID between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(Long value1, Long value2) {
            addCriterion("JOB_ID not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andGradeIdIsNull() {
            addCriterion("GRADE_ID is null");
            return (Criteria) this;
        }

        public Criteria andGradeIdIsNotNull() {
            addCriterion("GRADE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGradeIdEqualTo(Long value) {
            addCriterion("GRADE_ID =", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdNotEqualTo(Long value) {
            addCriterion("GRADE_ID <>", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdGreaterThan(Long value) {
            addCriterion("GRADE_ID >", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("GRADE_ID >=", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdLessThan(Long value) {
            addCriterion("GRADE_ID <", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdLessThanOrEqualTo(Long value) {
            addCriterion("GRADE_ID <=", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdIn(List<Long> values) {
            addCriterion("GRADE_ID in", values, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdNotIn(List<Long> values) {
            addCriterion("GRADE_ID not in", values, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdBetween(Long value1, Long value2) {
            addCriterion("GRADE_ID between", value1, value2, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdNotBetween(Long value1, Long value2) {
            addCriterion("GRADE_ID not between", value1, value2, "gradeId");
            return (Criteria) this;
        }

        public Criteria andActionTypeIsNull() {
            addCriterion("ACTION_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andActionTypeIsNotNull() {
            addCriterion("ACTION_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andActionTypeEqualTo(String value) {
            addCriterion("ACTION_TYPE =", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeNotEqualTo(String value) {
            addCriterion("ACTION_TYPE <>", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeGreaterThan(String value) {
            addCriterion("ACTION_TYPE >", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_TYPE >=", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeLessThan(String value) {
            addCriterion("ACTION_TYPE <", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeLessThanOrEqualTo(String value) {
            addCriterion("ACTION_TYPE <=", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeLike(String value) {
            addCriterion("ACTION_TYPE like", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeNotLike(String value) {
            addCriterion("ACTION_TYPE not like", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeIn(List<String> values) {
            addCriterion("ACTION_TYPE in", values, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeNotIn(List<String> values) {
            addCriterion("ACTION_TYPE not in", values, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeBetween(String value1, String value2) {
            addCriterion("ACTION_TYPE between", value1, value2, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeNotBetween(String value1, String value2) {
            addCriterion("ACTION_TYPE not between", value1, value2, "actionType");
            return (Criteria) this;
        }

        public Criteria andRefIdIsNull() {
            addCriterion("REF_ID is null");
            return (Criteria) this;
        }

        public Criteria andRefIdIsNotNull() {
            addCriterion("REF_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRefIdEqualTo(Long value) {
            addCriterion("REF_ID =", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotEqualTo(Long value) {
            addCriterion("REF_ID <>", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdGreaterThan(Long value) {
            addCriterion("REF_ID >", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdGreaterThanOrEqualTo(Long value) {
            addCriterion("REF_ID >=", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdLessThan(Long value) {
            addCriterion("REF_ID <", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdLessThanOrEqualTo(Long value) {
            addCriterion("REF_ID <=", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdIn(List<Long> values) {
            addCriterion("REF_ID in", values, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotIn(List<Long> values) {
            addCriterion("REF_ID not in", values, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdBetween(Long value1, Long value2) {
            addCriterion("REF_ID between", value1, value2, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotBetween(Long value1, Long value2) {
            addCriterion("REF_ID not between", value1, value2, "refId");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("SOURCE =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("SOURCE <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("SOURCE >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("SOURCE <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("SOURCE <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("SOURCE like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("SOURCE not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("SOURCE in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("SOURCE not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("SOURCE between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("SOURCE not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andTransferedByIsNull() {
            addCriterion("TRANSFERED_BY is null");
            return (Criteria) this;
        }

        public Criteria andTransferedByIsNotNull() {
            addCriterion("TRANSFERED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andTransferedByEqualTo(String value) {
            addCriterion("TRANSFERED_BY =", value, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByNotEqualTo(String value) {
            addCriterion("TRANSFERED_BY <>", value, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByGreaterThan(String value) {
            addCriterion("TRANSFERED_BY >", value, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFERED_BY >=", value, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByLessThan(String value) {
            addCriterion("TRANSFERED_BY <", value, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByLessThanOrEqualTo(String value) {
            addCriterion("TRANSFERED_BY <=", value, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByLike(String value) {
            addCriterion("TRANSFERED_BY like", value, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByNotLike(String value) {
            addCriterion("TRANSFERED_BY not like", value, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByIn(List<String> values) {
            addCriterion("TRANSFERED_BY in", values, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByNotIn(List<String> values) {
            addCriterion("TRANSFERED_BY not in", values, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByBetween(String value1, String value2) {
            addCriterion("TRANSFERED_BY between", value1, value2, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andTransferedByNotBetween(String value1, String value2) {
            addCriterion("TRANSFERED_BY not between", value1, value2, "transferedBy");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusIsNull() {
            addCriterion("ASSIGNMENT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusIsNotNull() {
            addCriterion("ASSIGNMENT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusEqualTo(String value) {
            addCriterion("ASSIGNMENT_STATUS =", value, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusNotEqualTo(String value) {
            addCriterion("ASSIGNMENT_STATUS <>", value, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusGreaterThan(String value) {
            addCriterion("ASSIGNMENT_STATUS >", value, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ASSIGNMENT_STATUS >=", value, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusLessThan(String value) {
            addCriterion("ASSIGNMENT_STATUS <", value, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusLessThanOrEqualTo(String value) {
            addCriterion("ASSIGNMENT_STATUS <=", value, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusLike(String value) {
            addCriterion("ASSIGNMENT_STATUS like", value, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusNotLike(String value) {
            addCriterion("ASSIGNMENT_STATUS not like", value, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusIn(List<String> values) {
            addCriterion("ASSIGNMENT_STATUS in", values, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusNotIn(List<String> values) {
            addCriterion("ASSIGNMENT_STATUS not in", values, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusBetween(String value1, String value2) {
            addCriterion("ASSIGNMENT_STATUS between", value1, value2, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusNotBetween(String value1, String value2) {
            addCriterion("ASSIGNMENT_STATUS not between", value1, value2, "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceIsNull() {
            addCriterion("HOUSING_ALLOWANCE is null");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceIsNotNull() {
            addCriterion("HOUSING_ALLOWANCE is not null");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceEqualTo(String value) {
            addCriterion("HOUSING_ALLOWANCE =", value, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceNotEqualTo(String value) {
            addCriterion("HOUSING_ALLOWANCE <>", value, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceGreaterThan(String value) {
            addCriterion("HOUSING_ALLOWANCE >", value, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSING_ALLOWANCE >=", value, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceLessThan(String value) {
            addCriterion("HOUSING_ALLOWANCE <", value, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceLessThanOrEqualTo(String value) {
            addCriterion("HOUSING_ALLOWANCE <=", value, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceLike(String value) {
            addCriterion("HOUSING_ALLOWANCE like", value, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceNotLike(String value) {
            addCriterion("HOUSING_ALLOWANCE not like", value, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceIn(List<String> values) {
            addCriterion("HOUSING_ALLOWANCE in", values, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceNotIn(List<String> values) {
            addCriterion("HOUSING_ALLOWANCE not in", values, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceBetween(String value1, String value2) {
            addCriterion("HOUSING_ALLOWANCE between", value1, value2, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceNotBetween(String value1, String value2) {
            addCriterion("HOUSING_ALLOWANCE not between", value1, value2, "housingAllowance");
            return (Criteria) this;
        }

        public Criteria andMentorIdIsNull() {
            addCriterion("MENTOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andMentorIdIsNotNull() {
            addCriterion("MENTOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMentorIdEqualTo(Long value) {
            addCriterion("MENTOR_ID =", value, "mentorId");
            return (Criteria) this;
        }

        public Criteria andMentorIdNotEqualTo(Long value) {
            addCriterion("MENTOR_ID <>", value, "mentorId");
            return (Criteria) this;
        }

        public Criteria andMentorIdGreaterThan(Long value) {
            addCriterion("MENTOR_ID >", value, "mentorId");
            return (Criteria) this;
        }

        public Criteria andMentorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("MENTOR_ID >=", value, "mentorId");
            return (Criteria) this;
        }

        public Criteria andMentorIdLessThan(Long value) {
            addCriterion("MENTOR_ID <", value, "mentorId");
            return (Criteria) this;
        }

        public Criteria andMentorIdLessThanOrEqualTo(Long value) {
            addCriterion("MENTOR_ID <=", value, "mentorId");
            return (Criteria) this;
        }

        public Criteria andMentorIdIn(List<Long> values) {
            addCriterion("MENTOR_ID in", values, "mentorId");
            return (Criteria) this;
        }

        public Criteria andMentorIdNotIn(List<Long> values) {
            addCriterion("MENTOR_ID not in", values, "mentorId");
            return (Criteria) this;
        }

        public Criteria andMentorIdBetween(Long value1, Long value2) {
            addCriterion("MENTOR_ID between", value1, value2, "mentorId");
            return (Criteria) this;
        }

        public Criteria andMentorIdNotBetween(Long value1, Long value2) {
            addCriterion("MENTOR_ID not between", value1, value2, "mentorId");
            return (Criteria) this;
        }

        public Criteria andInternshipIsNull() {
            addCriterion("IS_INTERNSHIP is null");
            return (Criteria) this;
        }

        public Criteria andInternshipIsNotNull() {
            addCriterion("IS_INTERNSHIP is not null");
            return (Criteria) this;
        }

        public Criteria andInternshipEqualTo(Boolean value) {
            addCriterion("IS_INTERNSHIP =", value, "internship");
            return (Criteria) this;
        }

        public Criteria andInternshipNotEqualTo(Boolean value) {
            addCriterion("IS_INTERNSHIP <>", value, "internship");
            return (Criteria) this;
        }

        public Criteria andInternshipGreaterThan(Boolean value) {
            addCriterion("IS_INTERNSHIP >", value, "internship");
            return (Criteria) this;
        }

        public Criteria andInternshipGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_INTERNSHIP >=", value, "internship");
            return (Criteria) this;
        }

        public Criteria andInternshipLessThan(Boolean value) {
            addCriterion("IS_INTERNSHIP <", value, "internship");
            return (Criteria) this;
        }

        public Criteria andInternshipLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_INTERNSHIP <=", value, "internship");
            return (Criteria) this;
        }

        public Criteria andInternshipIn(List<Boolean> values) {
            addCriterion("IS_INTERNSHIP in", values, "internship");
            return (Criteria) this;
        }

        public Criteria andInternshipNotIn(List<Boolean> values) {
            addCriterion("IS_INTERNSHIP not in", values, "internship");
            return (Criteria) this;
        }

        public Criteria andInternshipBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_INTERNSHIP between", value1, value2, "internship");
            return (Criteria) this;
        }

        public Criteria andInternshipNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_INTERNSHIP not between", value1, value2, "internship");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateIsNull() {
            addCriterion("EFFECTIVE_START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateIsNotNull() {
            addCriterion("EFFECTIVE_START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_START_DATE =", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_START_DATE <>", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_START_DATE >", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_START_DATE >=", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateLessThan(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_START_DATE <", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_START_DATE <=", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("EFFECTIVE_START_DATE in", values, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("EFFECTIVE_START_DATE not in", values, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EFFECTIVE_START_DATE between", value1, value2, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EFFECTIVE_START_DATE not between", value1, value2, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateIsNull() {
            addCriterion("EFFECTIVE_END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateIsNotNull() {
            addCriterion("EFFECTIVE_END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_END_DATE =", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_END_DATE <>", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_END_DATE >", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_END_DATE >=", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateLessThan(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_END_DATE <", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTIVE_END_DATE <=", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("EFFECTIVE_END_DATE in", values, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("EFFECTIVE_END_DATE not in", values, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EFFECTIVE_END_DATE between", value1, value2, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EFFECTIVE_END_DATE not between", value1, value2, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Long value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Long value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Long value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Long value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Long value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Long> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Long> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Long value1, Long value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Long value1, Long value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNull() {
            addCriterion("LAST_UPDATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNotNull() {
            addCriterion("LAST_UPDATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY =", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY <>", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThan(Long value) {
            addCriterion("LAST_UPDATED_BY >", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY >=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThan(Long value) {
            addCriterion("LAST_UPDATED_BY <", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThanOrEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY <=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIn(List<Long> values) {
            addCriterion("LAST_UPDATED_BY in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotIn(List<Long> values) {
            addCriterion("LAST_UPDATED_BY not in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByBetween(Long value1, Long value2) {
            addCriterion("LAST_UPDATED_BY between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotBetween(Long value1, Long value2) {
            addCriterion("LAST_UPDATED_BY not between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNull() {
            addCriterion("CREATION_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNotNull() {
            addCriterion("CREATION_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDateEqualTo(Date value) {
            addCriterion("CREATION_DATE =", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotEqualTo(Date value) {
            addCriterion("CREATION_DATE <>", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThan(Date value) {
            addCriterion("CREATION_DATE >", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATION_DATE >=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThan(Date value) {
            addCriterion("CREATION_DATE <", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATION_DATE <=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateIn(List<Date> values) {
            addCriterion("CREATION_DATE in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotIn(List<Date> values) {
            addCriterion("CREATION_DATE not in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateBetween(Date value1, Date value2) {
            addCriterion("CREATION_DATE between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATION_DATE not between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andActionTypeLikeInsensitive(String value) {
            addCriterion("upper(ACTION_TYPE) like", value.toUpperCase(), "actionType");
            return (Criteria) this;
        }

        public Criteria andSourceLikeInsensitive(String value) {
            addCriterion("upper(SOURCE) like", value.toUpperCase(), "source");
            return (Criteria) this;
        }

        public Criteria andTransferedByLikeInsensitive(String value) {
            addCriterion("upper(TRANSFERED_BY) like", value.toUpperCase(), "transferedBy");
            return (Criteria) this;
        }

        public Criteria andAssignmentStatusLikeInsensitive(String value) {
            addCriterion("upper(ASSIGNMENT_STATUS) like", value.toUpperCase(), "assignmentStatus");
            return (Criteria) this;
        }

        public Criteria andHousingAllowanceLikeInsensitive(String value) {
            addCriterion("upper(HOUSING_ALLOWANCE) like", value.toUpperCase(), "housingAllowance");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 19 18:47:54 ICT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PEA_PRIMARY_ASSIGNMENTS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}