package co.id.fifgroup.personneladmin.domain;

import java.io.Serializable;
import java.util.Date;

public class ProbationReview implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.PROBATION_REVIEW_ID
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private Long probationReviewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.PERSON_ID
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.COMPANY_ID
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.NOTES
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.EVALUATION_RESULT
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private String evaluationResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.TERMINATION_DATE
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private Date terminationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.PROBATION_STATUS
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private String probationStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.CREATED_BY
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.CREATION_DATE
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.LAST_UPDATED_BY
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PEA_PROBATION_REVIEWS.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PEA_PROBATION_REVIEWS
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.PROBATION_REVIEW_ID
     *
     * @return the value of PEA_PROBATION_REVIEWS.PROBATION_REVIEW_ID
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public Long getProbationReviewId() {
        return probationReviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.PROBATION_REVIEW_ID
     *
     * @param probationReviewId the value for PEA_PROBATION_REVIEWS.PROBATION_REVIEW_ID
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setProbationReviewId(Long probationReviewId) {
        this.probationReviewId = probationReviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.PERSON_ID
     *
     * @return the value of PEA_PROBATION_REVIEWS.PERSON_ID
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.PERSON_ID
     *
     * @param personId the value for PEA_PROBATION_REVIEWS.PERSON_ID
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.COMPANY_ID
     *
     * @return the value of PEA_PROBATION_REVIEWS.COMPANY_ID
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.COMPANY_ID
     *
     * @param companyId the value for PEA_PROBATION_REVIEWS.COMPANY_ID
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.NOTES
     *
     * @return the value of PEA_PROBATION_REVIEWS.NOTES
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.NOTES
     *
     * @param notes the value for PEA_PROBATION_REVIEWS.NOTES
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.EVALUATION_RESULT
     *
     * @return the value of PEA_PROBATION_REVIEWS.EVALUATION_RESULT
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public String getEvaluationResult() {
        return evaluationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.EVALUATION_RESULT
     *
     * @param evaluationResult the value for PEA_PROBATION_REVIEWS.EVALUATION_RESULT
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setEvaluationResult(String evaluationResult) {
        this.evaluationResult = evaluationResult == null ? null : evaluationResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.TERMINATION_DATE
     *
     * @return the value of PEA_PROBATION_REVIEWS.TERMINATION_DATE
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public Date getTerminationDate() {
        return terminationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.TERMINATION_DATE
     *
     * @param terminationDate the value for PEA_PROBATION_REVIEWS.TERMINATION_DATE
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setTerminationDate(Date terminationDate) {
        this.terminationDate = terminationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.PROBATION_STATUS
     *
     * @return the value of PEA_PROBATION_REVIEWS.PROBATION_STATUS
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public String getProbationStatus() {
        return probationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.PROBATION_STATUS
     *
     * @param probationStatus the value for PEA_PROBATION_REVIEWS.PROBATION_STATUS
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setProbationStatus(String probationStatus) {
        this.probationStatus = probationStatus == null ? null : probationStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.CREATED_BY
     *
     * @return the value of PEA_PROBATION_REVIEWS.CREATED_BY
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.CREATED_BY
     *
     * @param createdBy the value for PEA_PROBATION_REVIEWS.CREATED_BY
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.CREATION_DATE
     *
     * @return the value of PEA_PROBATION_REVIEWS.CREATION_DATE
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.CREATION_DATE
     *
     * @param creationDate the value for PEA_PROBATION_REVIEWS.CREATION_DATE
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.LAST_UPDATED_BY
     *
     * @return the value of PEA_PROBATION_REVIEWS.LAST_UPDATED_BY
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for PEA_PROBATION_REVIEWS.LAST_UPDATED_BY
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PEA_PROBATION_REVIEWS.LAST_UPDATE_DATE
     *
     * @return the value of PEA_PROBATION_REVIEWS.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PEA_PROBATION_REVIEWS.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for PEA_PROBATION_REVIEWS.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Jul 09 14:59:17 ICT 2013
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}