DROP TABLE WOS_ORGANIZATIONS CASCADE CONSTRAINTS
;
DROP TABLE WOS_ORGANIZATION_CONTACTS CASCADE CONSTRAINTS
;
DROP TABLE WOS_ORGANIZATION_INFOS CASCADE CONSTRAINTS
;
DROP TABLE WOS_ORGANIZATION_VERSIONS CASCADE CONSTRAINTS
;
DROP TABLE WOS_ORG_COST_PROPORTIONS CASCADE CONSTRAINTS
;

DROP SEQUENCE WOS_ORGANIZATIONS_S;
DROP SEQUENCE WOS_ORGANIZATION_VERSIONS_S;
DROP SEQUENCE WOS_ORGANIZATION_CONTACTS_S;
DROP SEQUENCE WOS_ORGANIZATION_INFOS_S;
DROP SEQUENCE WOS_ORG_COST_PROPORTIONS_S;

CREATE SEQUENCE WOS_ORGANIZATIONS_S;
CREATE SEQUENCE WOS_ORGANIZATION_VERSIONS_S;
CREATE SEQUENCE WOS_ORGANIZATION_CONTACTS_S;
CREATE SEQUENCE WOS_ORGANIZATION_INFOS_S;
CREATE SEQUENCE WOS_ORG_COST_PROPORTIONS_S;

CREATE TABLE WOS_ORGANIZATIONS
(
	ORGANIZATION_ID    NUMBER(15) NOT NULL,
	COMPANY_ID         NUMBER(15) NOT NULL,
	ORGANIZATION_CODE  VARCHAR2(50) NOT NULL,
	ORGANIZATION_NAME  VARCHAR2(240) NOT NULL,
	CREATED_BY         NUMBER(15),
	CREATION_DATE      DATE,
	LAST_UPDATED_BY    NUMBER(15),
	LAST_UPDATE_DATE   DATE
)
;

COMMENT ON TABLE WOS_ORGANIZATIONS IS 'Tabel ini digunakan untuk menyimpan data Organisasi yang bersifat immutable.'
;

CREATE TABLE WOS_ORGANIZATION_CONTACTS
(
	ORGANIZATION_VERSION_ID  NUMBER(15) NOT NULL,
	ORGANIZATION_ID          NUMBER(15) NOT NULL,
	TYPE                     VARCHAR2(50) NOT NULL,
	INFORMATION              VARCHAR2(150) NOT NULL
)
;


CREATE TABLE WOS_ORGANIZATION_INFOS
(
	ORGANIZATION_VERSION_ID  NUMBER(15) NOT NULL,
	INFO_ID                  NUMBER(15) NOT NULL,
	ORGANIZATION_ID          NUMBER(15) NOT NULL,
	INFO_VALUE               VARCHAR2(100)
)
;

COMMENT ON TABLE WOS_ORGANIZATION_INFOS IS 'Default Other Information for Organization :  Is HO Branch (boolean) Is Approver (boolean)'
;

CREATE TABLE WOS_ORGANIZATION_VERSIONS
(
	ORGANIZATION_VERSION_ID  NUMBER(15) NOT NULL,
	ORGANIZATION_ID          NUMBER(15),
	VERSION_NUMBER           NUMBER(15) NOT NULL,
	EFFECTIVE_START_DATE     DATE NOT NULL,
	EFFECTIVE_END_DATE       DATE NOT NULL,
	DESCRIPTION              VARCHAR2(255),
	LEVEL_CODE               VARCHAR2(50) NOT NULL,
	NPWP                     VARCHAR2(50) NOT NULL,
	KPP_CODE                 VARCHAR2(30) NOT NULL,
	LOCATION_ID              NUMBER(15) NOT NULL,
	ORGANIZATION_HEAD_ID     NUMBER(15) NOT NULL,
	IS_HEAD_BY_EMPLOYEE      NUMBER(1),
	HEAD_BY_EMPLOYEE_ID      NUMBER(15),
	PIC_ID                   NUMBER(15),
	IS_HEAD_OFFICE           NUMBER(1),
	ORGANIZATION_SPV_ID      NUMBER(15) NOT NULL,
	BRANCH_CODE              VARCHAR2(30) NOT NULL,
	COST_CENTER              VARCHAR2(50) NOT NULL,
	ADDRESS                  VARCHAR2(255) NOT NULL,
	KELURAHAN_CODE           VARCHAR2(10),
	KECAMATAN_CODE           VARCHAR2(10),
	ZIP_CODE                 VARCHAR2(15),
	WORKING_SCHEDULE_ID      NUMBER(15)
)
;


CREATE TABLE WOS_ORG_COST_PROPORTIONS
(
	ORGANIZATION_VERSION_ID  NUMBER(15),
	PRODUCT_CODE             VARCHAR2(50) NOT NULL,
	PERCENTAGE               NUMBER(5,2)
)
;



ALTER TABLE WOS_ORGANIZATIONS
	ADD CONSTRAINT WOS_ORGANIZATIONS_U1 UNIQUE (ORGANIZATION_CODE)
 USING INDEX 
;

CREATE INDEX WOS_ORGANIZATION_VERSIONS_N1 ON WOS_ORGANIZATION_VERSIONS
(VERSION_NUMBER ASC)
;

ALTER TABLE WOS_ORG_COST_PROPORTIONS
	ADD CONSTRAINT WOS_ORG_COST_PROPORTIONS_U1 UNIQUE (PRODUCT_CODE, ORGANIZATION_VERSION_ID)
 USING INDEX 
;

ALTER TABLE WOS_ORGANIZATIONS ADD CONSTRAINT WOS_ORGANIZATIONS_PK 
	PRIMARY KEY (ORGANIZATION_ID) 
 USING INDEX 
;

ALTER TABLE WOS_ORGANIZATION_CONTACTS ADD CONSTRAINT WOS_ORGANIZATION_CONTACTS_PK 
	PRIMARY KEY (ORGANIZATION_VERSION_ID, TYPE) 
 USING INDEX 
;

ALTER TABLE WOS_ORGANIZATION_INFOS ADD CONSTRAINT WOS_ORGANIZATION_INFOS_PK 
	PRIMARY KEY (ORGANIZATION_VERSION_ID, INFO_ID) 
 USING INDEX 
;

ALTER TABLE WOS_ORGANIZATION_VERSIONS ADD CONSTRAINT WOS_ORGANIZATION_VERSIONS_PK 
	PRIMARY KEY (ORGANIZATION_VERSION_ID) 
 USING INDEX 
;



ALTER TABLE WOS_ORGANIZATION_CONTACTS ADD CONSTRAINT WOS_ORGANIZATION_CONTACTS_FK 
	FOREIGN KEY (ORGANIZATION_VERSION_ID) REFERENCES WOS_ORGANIZATION_VERSIONS (ORGANIZATION_VERSION_ID)
;

ALTER TABLE WOS_ORGANIZATION_INFOS ADD CONSTRAINT WOS_ORG_INFO_FK 
	FOREIGN KEY (ORGANIZATION_VERSION_ID) REFERENCES WOS_ORGANIZATION_VERSIONS (ORGANIZATION_VERSION_ID)
;

ALTER TABLE WOS_ORGANIZATION_VERSIONS ADD CONSTRAINT WOS_ORGANIZATION_VERSIONS_FK1 
	FOREIGN KEY (ORGANIZATION_ID) REFERENCES WOS_ORGANIZATIONS (ORGANIZATION_ID)
;

ALTER TABLE WOS_ORG_COST_PROPORTIONS ADD CONSTRAINT WOS_ORG_COST_PROPORTIONS_FK1 
	FOREIGN KEY (ORGANIZATION_VERSION_ID) REFERENCES WOS_ORGANIZATION_VERSIONS (ORGANIZATION_VERSION_ID)
;
