DROP TABLE WOS_ORGANIZATION_LEVELS CASCADE CONSTRAINTS
;

DROP SEQUENCE WOS_ORGANIZATION_LEVELS_S;
CREATE SEQUENCE WOS_ORGANIZATION_LEVELS_S;

CREATE TABLE WOS_ORGANIZATION_LEVELS
(
	LEVEL_ID       NUMBER(15) NOT NULL,
	LEVEL_CODE     VARCHAR2(100) NOT NULL,
	COMPANY_ID     NUMBER(15) NOT NULL,
	LEVEL_NAME     VARCHAR2(100) NOT NULL,
	DESCRIPTION    VARCHAR2(100) NOT NULL,
	COLOR          VARCHAR2(6) NOT NULL,
	DATE_FROM      DATE NOT NULL,
	DATE_TO        DATE NOT NULL,
	CREATED_BY     NUMBER(15),
	CREATION_DATE  DATE ,
	LAST_UPDATED_BY     NUMBER(15),
	LAST_UPDATE_DATE    DATE
)
;


ALTER TABLE WOS_ORGANIZATION_LEVELS ADD CONSTRAINT WOS_ORGANIZATION_LEVELS_PK 
	PRIMARY KEY (LEVEL_ID) 
 USING INDEX 
;

