--------------------------------------------------------
--  File created - Monday-November-19-2012   
--------------------------------------------------------
DROP TABLE "AVM"."AVM";
DROP TABLE "AVM"."AVM_APPROVAL_HISTORY";
DROP TABLE "AVM"."AVM_APPROVER";
DROP TABLE "AVM"."AVM_LEVEL";
DROP TABLE "AVM"."AVM_RULE_LOOKUP_DETAIL";
DROP TABLE "AVM"."AVM_RULE_LOOKUP_HEADER";
DROP TABLE "AVM"."AVM_RULE_MAPPING";
DROP TABLE "AVM"."AVM_TRANSACTION";
DROP TABLE "AVM"."AVM_TRX_MAPPING";
DROP SEQUENCE "AVM"."AUTO_INCREMENT";
DROP SEQUENCE "AVM"."AVM_RULE_MAPPING_SEQUENCE";
--------------------------------------------------------
--  DDL for Sequence AUTO_INCREMENT
--------------------------------------------------------

   CREATE SEQUENCE  "AVM"."AUTO_INCREMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence AVM_RULE_MAPPING_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "AVM"."AVM_RULE_MAPPING_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AVM
--------------------------------------------------------

  CREATE TABLE "AVM"."AVM" 
   (	"AVM_ID" RAW(16), 
	"AVM_NAME" VARCHAR2(50 BYTE), 
	"THRESHOLD_TYPE" NUMBER(38,0), 
	"THRESHOLD" NUMBER(*,0), 
	"VERSION" NUMBER DEFAULT NULL, 
	"START_DATE" DATE, 
	"END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVM_APPROVAL_HISTORY
--------------------------------------------------------

  CREATE TABLE "AVM"."AVM_APPROVAL_HISTORY" 
   (	"SEQUENCE_NUMBER" NUMBER(38,0), 
	"APPROVER_ID" RAW(16), 
	"AVM_TRX_ID" RAW(16), 
	"LEVEL_SEQUENCE" NUMBER(38,0) DEFAULT NULL, 
	"AVM_ACTION_TYPE" NUMBER(38,0) DEFAULT 0, 
	"AVM_ACTION_TIMESTAMP" TIMESTAMP (6) DEFAULT NULL, 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"PRIORITY" NUMBER(*,0), 
	"ORGANIZATION_ID" NUMBER, 
	"AVM_RECEIVED_TIMESTAMP" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVM_APPROVER
--------------------------------------------------------

  CREATE TABLE "AVM"."AVM_APPROVER" 
   (	"AVM_ID" RAW(16), 
	"LEVEL_SEQUENCE" NUMBER(38,0), 
	"APPROVER_ID" RAW(16), 
	"PRIORITY" NUMBER(38,0), 
	"VERSION" NUMBER DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVM_LEVEL
--------------------------------------------------------

  CREATE TABLE "AVM"."AVM_LEVEL" 
   (	"AVM_ID" RAW(16), 
	"LEVEL_SEQUENCE" NUMBER(3,0), 
	"NUMBER_OF_APPROVALS" NUMBER(3,0), 
	"RULE" VARCHAR2(500 CHAR), 
	"LEVEL_NAME" VARCHAR2(300 CHAR), 
	"VERSION" NUMBER DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVM_RULE_LOOKUP_DETAIL
--------------------------------------------------------

  CREATE TABLE "AVM"."AVM_RULE_LOOKUP_DETAIL" 
   (	"LOOKUP_DETAIL_ID" NUMBER, 
	"LOOKUP_DETAIL_VALUE" VARCHAR2(200 CHAR), 
	"DESCRIPTION" VARCHAR2(300 CHAR), 
	"ACTIVE_STATUS" NUMBER(1,0) DEFAULT 1, 
	"LOOKUP_HEADER_ID" VARCHAR2(100 CHAR), 
	"LOOKUP_DETAIL_CODE" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVM_RULE_LOOKUP_HEADER
--------------------------------------------------------

  CREATE TABLE "AVM"."AVM_RULE_LOOKUP_HEADER" 
   (	"LOOKUP_HEADER_ID" VARCHAR2(200 CHAR), 
	"DESCRIPTION" VARCHAR2(300 CHAR), 
	"VALUE_DOMAIN" VARCHAR2(200 CHAR), 
	"WITH_VALUE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVM_RULE_MAPPING
--------------------------------------------------------

  CREATE TABLE "AVM"."AVM_RULE_MAPPING" 
   (	"MAPPING_ID" NUMBER(*,0), 
	"CLASS_NAME" VARCHAR2(300 CHAR), 
	"METHOD_NAME" VARCHAR2(255 CHAR), 
	"ATTRIBUTE_LABEL" VARCHAR2(255 CHAR), 
	"LOOKUP_HEADER_ID" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVM_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "AVM"."AVM_TRANSACTION" 
   (	"AVM_TRX_ID" RAW(16), 
	"AVM_ID" RAW(16), 
	"LEVEL_SEQUENCE" NUMBER(38,0), 
	"REMAINING_APPROVAL" NUMBER(38,0), 
	"AVM_TRX_STATUS" NUMBER(38,0) DEFAULT 0, 
	"SERIALIZED_DATA" BLOB, 
	"AVM_TIMESTAMP" TIMESTAMP (6), 
	"TRX_TYPE" NUMBER(*,0), 
	"VERSION" NUMBER DEFAULT NULL, 
	"SUBJECT" VARCHAR2(512 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("SERIALIZED_DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "AVM"."AVM_TRANSACTION"."AVM_TRX_STATUS" IS '0 = in progress; 1 = finalized; -1 = rejected; -2 = cancelled';
--------------------------------------------------------
--  DDL for Table AVM_TRX_MAPPING
--------------------------------------------------------

  CREATE TABLE "AVM"."AVM_TRX_MAPPING" 
   (	"AVM_ID" RAW(16), 
	"TRX_TYPE" NUMBER, 
	"AVM_STATUS" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVM_LEVEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVM"."AVM_LEVEL_PK" ON "AVM"."AVM_LEVEL" ("AVM_ID", "LEVEL_SEQUENCE", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVM_TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVM"."AVM_TRANSACTION_PK" ON "AVM"."AVM_TRANSACTION" ("AVM_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVM_RULE_LOOKUP_HEADER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVM"."AVM_RULE_LOOKUP_HEADER_PK" ON "AVM"."AVM_RULE_LOOKUP_HEADER" ("LOOKUP_HEADER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVM_APPROVAL_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVM"."AVM_APPROVAL_HISTORY_PK" ON "AVM"."AVM_APPROVAL_HISTORY" ("SEQUENCE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVM_APPROVER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVM"."AVM_APPROVER_PK" ON "AVM"."AVM_APPROVER" ("AVM_ID", "LEVEL_SEQUENCE", "APPROVER_ID", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVM"."AVM_PK" ON "AVM"."AVM" ("AVM_ID", "VERSION", "START_DATE", "END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVM_TRX_MAPPING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVM"."AVM_TRX_MAPPING_PK" ON "AVM"."AVM_TRX_MAPPING" ("AVM_ID", "TRX_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVM_RULE_MAPPING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVM"."AVM_RULE_MAPPING_PK" ON "AVM"."AVM_RULE_MAPPING" ("MAPPING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVM_RULE_LOOKUP_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVM"."AVM_RULE_LOOKUP_DETAIL_PK" ON "AVM"."AVM_RULE_LOOKUP_DETAIL" ("LOOKUP_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AVM_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "AVM"."AVM_TRANSACTION" ADD CONSTRAINT "AVM_TRANSACTION_PK" PRIMARY KEY ("AVM_TRX_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AVM"."AVM_TRANSACTION" MODIFY ("AVM_TRX_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AVM_TRX_MAPPING
--------------------------------------------------------

  ALTER TABLE "AVM"."AVM_TRX_MAPPING" ADD CONSTRAINT "AVM_TRX_MAPPING_PK" PRIMARY KEY ("AVM_ID", "TRX_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AVM"."AVM_TRX_MAPPING" MODIFY ("AVM_STATUS" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_TRX_MAPPING" MODIFY ("TRX_TYPE" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_TRX_MAPPING" MODIFY ("AVM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AVM_APPROVAL_HISTORY
--------------------------------------------------------

  ALTER TABLE "AVM"."AVM_APPROVAL_HISTORY" ADD CONSTRAINT "AVM_APPROVAL_HISTORY_PK" PRIMARY KEY ("SEQUENCE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AVM"."AVM_APPROVAL_HISTORY" MODIFY ("AVM_ACTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_APPROVAL_HISTORY" MODIFY ("LEVEL_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_APPROVAL_HISTORY" MODIFY ("AVM_TRX_ID" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_APPROVAL_HISTORY" MODIFY ("APPROVER_ID" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_APPROVAL_HISTORY" MODIFY ("SEQUENCE_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AVM_RULE_MAPPING
--------------------------------------------------------

  ALTER TABLE "AVM"."AVM_RULE_MAPPING" ADD CONSTRAINT "AVM_RULE_MAPPING_PK" PRIMARY KEY ("MAPPING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AVM"."AVM_RULE_MAPPING" MODIFY ("LOOKUP_HEADER_ID" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_RULE_MAPPING" MODIFY ("ATTRIBUTE_LABEL" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_RULE_MAPPING" MODIFY ("METHOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_RULE_MAPPING" MODIFY ("CLASS_NAME" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_RULE_MAPPING" MODIFY ("MAPPING_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AVM_LEVEL
--------------------------------------------------------

  ALTER TABLE "AVM"."AVM_LEVEL" ADD CONSTRAINT "AVM_LEVEL_PK" PRIMARY KEY ("AVM_ID", "LEVEL_SEQUENCE", "VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AVM"."AVM_LEVEL" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_LEVEL" MODIFY ("NUMBER_OF_APPROVALS" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_LEVEL" MODIFY ("LEVEL_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_LEVEL" MODIFY ("AVM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AVM
--------------------------------------------------------

  ALTER TABLE "AVM"."AVM" MODIFY ("AVM_NAME" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM" MODIFY ("AVM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AVM_APPROVER
--------------------------------------------------------

  ALTER TABLE "AVM"."AVM_APPROVER" ADD CONSTRAINT "AVM_APPROVER_PK" PRIMARY KEY ("AVM_ID", "LEVEL_SEQUENCE", "APPROVER_ID", "VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AVM"."AVM_APPROVER" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_APPROVER" MODIFY ("APPROVER_ID" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_APPROVER" MODIFY ("LEVEL_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "AVM"."AVM_APPROVER" MODIFY ("AVM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger AVM_RULE_MAPPING_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVM"."AVM_RULE_MAPPING_TRIGGER" 
BEFORE INSERT ON AVM_RULE_MAPPING
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT AVM_RULE_MAPPING_SEQUENCE.nextval INTO :NEW.MAPPING_ID FROM dual;
END;
/
ALTER TRIGGER "AVM"."AVM_RULE_MAPPING_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HISTORY_AUTO_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVM"."HISTORY_AUTO_INCREMENT" 
BEFORE INSERT ON AVM_APPROVAL_HISTORY 
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT AUTO_INCREMENT.nextval INTO :NEW.SEQUENCE_NUMBER FROM dual;
END;
/
ALTER TRIGGER "AVM"."HISTORY_AUTO_INCREMENT" ENABLE;
