DROP SEQUENCE ELR_DEC_TABLES_S;

DROP SEQUENCE ELR_DEC_TBL_COLUMNS_S;

DROP SEQUENCE ELR_DEC_TBL_ROWS_S;

DROP TABLE ELR_DEC_TABLES CASCADE CONSTRAINTS;
DROP TABLE ELR_DEC_TBL_COLUMNS CASCADE CONSTRAINTS;
DROP TABLE ELR_DEC_TBL_MODELS CASCADE CONSTRAINTS;
DROP TABLE ELR_DEC_TBL_ROWS CASCADE CONSTRAINTS;
DROP TABLE ELR_FACT_TYPE_FIELDS CASCADE CONSTRAINTS;
DROP TABLE ELR_FACT_TYPES CASCADE CONSTRAINTS;

CREATE TABLE ELR_DEC_TABLES
(
	DEC_TABLE_ID           NUMBER(15) NOT NULL,
	MODEL_ID               VARCHAR2(50) NOT NULL,
	VERSION_NUMBER         NUMBER(10) NOT NULL,
	MODULE_ID              NUMBER(15),
	SETUP_TYPE_ID          NUMBER(15),
	SETUP_TYPE_VERSION_ID  NUMBER(15),
	CREATED_BY             NUMBER(15),
	CREATION_DATE          DATE,
	LAST_UPDATED_BY        NUMBER(15),
	LAST_UPDATE_DATE       DATE
);


CREATE TABLE ELR_DEC_TBL_COLUMNS
(
	COLUMN_ID         NUMBER(15) NOT NULL,
	MODEL_ID          VARCHAR2(50) NOT NULL,
	VERSION_NUMBER    NUMBER(10) NOT NULL,
	COLUMN_TYPE       VARCHAR2(30) NOT NULL,
	COLUMN_NAME       VARCHAR2(150) NOT NULL,
	FACT_TYPE_ID      VARCHAR2(50) NOT NULL,
	FIELD_ID          VARCHAR2(50) NOT NULL,
	OPERATOR          VARCHAR2(20),
	VALUE_TYPE        VARCHAR2(20) NOT NULL,
	VALUE_LIST        VARCHAR2(1000),
	CREATED_BY        NUMBER(15),
	CREATION_DATE     DATE,
	LAST_UPDATED_BY   NUMBER(15),
	LAST_UPDATE_DATE  DATE
);


CREATE TABLE ELR_DEC_TBL_MODELS
(
	MODEL_ID          VARCHAR2(50) NOT NULL,
	MODEL_NAME        VARCHAR2(150) NOT NULL,
	VERSION_NUMBER    NUMBER(10) NOT NULL,
	CREATED_BY        NUMBER(15),
	CREATION_DATE     DATE,
	LAST_UPDATED_BY   NUMBER(15),
	LAST_UPDATE_DATE  DATE
);


CREATE TABLE ELR_DEC_TBL_ROWS
(
	ROW_ID            NUMBER(15) NOT NULL,
	DEC_TABLE_ID      NUMBER(15),
	CONDITIONS        VARCHAR2(4000),
	RESULTS           VARCHAR2(4000),
	DRL               CLOB,
	CREATED_BY        NUMBER(15),
	CREATION_DATE     DATE,
	LAST_UPDATED_BY   NUMBER(15),
	LAST_UPDATE_DATE  DATE
);


CREATE TABLE ELR_FACT_TYPE_FIELDS
(
	FACT_TYPE_ID      VARCHAR2(50) NOT NULL,
	FIELD_ID          VARCHAR2(50) NOT NULL,
	FIELD_NAME        VARCHAR2(150) NOT NULL,
	FIELD_TYPE        VARCHAR2(50) NOT NULL,
	LOOKUP_NAME       VARCHAR2(150),
	CREATED_BY        NUMBER(15),
	CREATION_DATE     DATE,
	LAST_UPDATED_BY   NUMBER(15),
	LAST_UPDATE_DATE  DATE
);


CREATE TABLE ELR_FACT_TYPES
(
	FACT_TYPE_ID      VARCHAR2(50) NOT NULL,
	COMPANY_ID        NUMBER(15) NOT NULL,
	FACT_TYPE_NAME    VARCHAR2(150) NOT NULL,
	RETRIEVAL_MODE    VARCHAR2(50) NOT NULL,
	SQL_QUERY         CLOB,
	CREATED_BY        NUMBER(15),
	CREATION_DATE     DATE,
	LAST_UPDATED_BY   NUMBER(15),
	LAST_UPDATE_DATE  DATE
);



CREATE INDEX ELR_DEC_TABLES_FK1 ON ELR_DEC_TABLES
(MODEL_ID ASC, VERSION_NUMBER ASC)
TABLESPACE  HCMSX_01;

ALTER TABLE ELR_DEC_TBL_COLUMNS
ADD CONSTRAINT ELR_DEC_TBL_COLUMNS_CHK1 CHECK (OPERATOR IN('EQUALS', 
	'GREATER_THAN', 
	'LOWER_THAN', 
	'GREATER_THAN_EQUAL', 
	'LOWER_THAN_EQUAL', 
	'IN'));

ALTER TABLE ELR_DEC_TBL_COLUMNS
ADD CONSTRAINT ELR_DEC_TBL_COLUMNS_CHK2 CHECK (COLUMN_TYPE IN ('CONDITION', 'RESULT'));

CREATE INDEX ELR_DEC_TBL_COLUMNS_FK1 ON ELR_DEC_TBL_COLUMNS
(MODEL_ID ASC, VERSION_NUMBER ASC)
TABLESPACE  HCMSX_01;

CREATE INDEX ELR_DEC_TBL_COLUMNS_FK2 ON ELR_DEC_TBL_COLUMNS
(FACT_TYPE_ID ASC, FIELD_ID ASC)
TABLESPACE  HCMSX_01;

CREATE INDEX ELR_DEC_TBL_ROWS_FK1 ON ELR_DEC_TBL_ROWS
(DEC_TABLE_ID ASC)
TABLESPACE  HCMSX_01;

ALTER TABLE ELR_FACT_TYPE_FIELDS
ADD CONSTRAINT ELR_FACT_TYPE_FIELDS_CHK1 CHECK (FIELD_TYPE IN ('TEXT', 'NUMBER', 'DATE', 'LOOKUP'));

CREATE INDEX ELR_FACT_TYPE_FK1 ON ELR_FACT_TYPE_FIELDS
(FACT_TYPE_ID ASC)
TABLESPACE  HCMSX_01;

ALTER TABLE ELR_FACT_TYPES
ADD CONSTRAINT ELR_FACT_TYPES_CHK1 CHECK (RETRIEVAL_MODE IN ('SUPPLIED', 'QUERY'));

ALTER TABLE ELR_DEC_TABLES ADD CONSTRAINT ELR_DEC_TABLES_PK 
	PRIMARY KEY (DEC_TABLE_ID) 
 USING INDEX 
TABLESPACE  HCMSX_01;

ALTER TABLE ELR_DEC_TBL_COLUMNS ADD CONSTRAINT ELR_DEC_TBL_COLUMNS_PK 
	PRIMARY KEY (COLUMN_ID) 
 USING INDEX 
TABLESPACE  HCMSX_01;

ALTER TABLE ELR_DEC_TBL_MODELS ADD CONSTRAINT ELR_DEC_TBL_MODELS_PK 
	PRIMARY KEY (MODEL_ID, VERSION_NUMBER) 
 USING INDEX 
TABLESPACE  HCMSX_01;

ALTER TABLE ELR_DEC_TBL_ROWS ADD CONSTRAINT ELR_DEC_TBL_ROWS_PK 
	PRIMARY KEY (ROW_ID) 
 USING INDEX 
TABLESPACE  HCMSX_01;

ALTER TABLE ELR_FACT_TYPE_FIELDS ADD CONSTRAINT ELR_FACT_TYPE_FIELDS_PK 
	PRIMARY KEY (FACT_TYPE_ID, FIELD_ID) 
 USING INDEX 
TABLESPACE  HCMSX_01;

ALTER TABLE ELR_FACT_TYPES ADD CONSTRAINT ELR_FACT_TYPES_PK 
	PRIMARY KEY (FACT_TYPE_ID) 
 USING INDEX 
TABLESPACE  HCMSX_01;



ALTER TABLE ELR_DEC_TABLES ADD CONSTRAINT ELR_DEC_TABLES_FK1 
	FOREIGN KEY (MODEL_ID, VERSION_NUMBER) REFERENCES ELR_DEC_TBL_MODELS (MODEL_ID, VERSION_NUMBER);

ALTER TABLE ELR_DEC_TBL_COLUMNS ADD CONSTRAINT ELR_DEC_TBL_COLUMNS_FK1 
	FOREIGN KEY (MODEL_ID, VERSION_NUMBER) REFERENCES ELR_DEC_TBL_MODELS (MODEL_ID, VERSION_NUMBER);

ALTER TABLE ELR_DEC_TBL_COLUMNS ADD CONSTRAINT ELR_DEC_TBL_COLUMNS_FK2 
	FOREIGN KEY (FACT_TYPE_ID, FIELD_ID) REFERENCES ELR_FACT_TYPE_FIELDS (FACT_TYPE_ID, FIELD_ID);

ALTER TABLE ELR_DEC_TBL_ROWS ADD CONSTRAINT ELR_DEC_TBL_ROWS_FK1 
	FOREIGN KEY (DEC_TABLE_ID) REFERENCES ELR_DEC_TABLES (DEC_TABLE_ID);

ALTER TABLE ELR_FACT_TYPE_FIELDS ADD CONSTRAINT ELR_FACT_TYPE_FK1 
	FOREIGN KEY (FACT_TYPE_ID) REFERENCES ELR_FACT_TYPES (FACT_TYPE_ID);





CREATE SEQUENCE ELR_DEC_TABLES_S;

CREATE SEQUENCE ELR_DEC_TBL_COLUMNS_S;

CREATE SEQUENCE ELR_DEC_TBL_ROWS_S;
