package co.id.fifgroup.ssoa.dao;


import co.id.fifgroup.ssoa.domain.Parameter;
import co.id.fifgroup.ssoa.domain.ParameterExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int countByExample(ParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int insert(Parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int insertSelective(Parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    List<Parameter> selectByExampleWithRowbounds(ParameterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    List<Parameter> selectByExample(ParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    Parameter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int updateByExampleSelective(@Param("record") Parameter record, @Param("example") ParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int updateByExample(@Param("record") Parameter record, @Param("example") ParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int updateByPrimaryKeySelective(Parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int updateByPrimaryKey(Parameter record);
}