package co.id.fifgroup.ssoa.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.ssoa.domain.SSOALocation;
import co.id.fifgroup.ssoa.domain.SSOALocationExample;

public interface SSOALocationMapper {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_PARAMETER_DTL
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
	SSOALocation selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_PARAMETER_DTL
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    List<SSOALocation> selectLocation(@Param("branchId")Long branchId, @Param("companyId")Long companyId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    List<SSOALocation> selectByExampleWithRowbounds(SSOALocationExample example, RowBounds rowBounds);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int countByExample(SSOALocationExample example);
    
    

    
    
}