package co.id.fifgroup.ssoa.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.id.fifgroup.ssoa.domain.Assets;
import co.id.fifgroup.ssoa.domain.StockOpnameDetail;
import co.id.fifgroup.ssoa.domain.StockOpnameDetailExample;
import co.id.fifgroup.ssoa.domain.StockOpnameUnregAssets;
import co.id.fifgroup.ssoa.domain.StockOpnameUnregAssetsExample;
import co.id.fifgroup.ssoa.dto.StockOpnameUnregAssetsDTO;

public interface StockOpnameUnregAssetsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table SAM_PARAMETER_DTL
	 *
	 * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table SAM_PARAMETER_DTL
	 *
	 * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
	 */
	StockOpnameUnregAssetsDTO selectByPrimaryKey(Long id);
	
	StockOpnameUnregAssetsDTO selectByHeaderIdAndAssetId(@Param("soId")Long soId, @Param("assetId")Long assetId);
	
	int updateOpnameStatus(StockOpnameUnregAssetsDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table SAM_PARAMETER_DTL
	 *
	 * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
	 */
	List<StockOpnameUnregAssetsDTO> selectByHeaderKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table SAM_PARAMETER_DTL
	 *
	 * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
	 */
	List<Assets> selectByBranchCode(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table SAM_PARAMETER_DTL
	 *
	 * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
	 */
	int updateByPrimaryKey(StockOpnameUnregAssetsDTO record);
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_PARAMETER_DTL
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int insert(StockOpnameUnregAssetsDTO record);
    
    List<StockOpnameUnregAssetsDTO> selectByExample(StockOpnameUnregAssetsExample stockOpnameUnregAssetsExample);
    
    int updateByExampleSelective(@Param("record") StockOpnameUnregAssets record, @Param("example") StockOpnameUnregAssetsExample example);

}