package co.id.fifgroup.ssoa.dao;


import co.id.fifgroup.ssoa.domain.StockOpnameUnregAssetImg;
import co.id.fifgroup.ssoa.domain.StockOpnameUnregAssetImgExample;
import co.id.fifgroup.ssoa.dto.StockOpnameUnregAssetImgDTO;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StockOpnameUnregAssetImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int countByExample(StockOpnameUnregAssetImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int deleteByPrimaryKey(Long id);
    
    int deleteByHeaderKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int insert(StockOpnameUnregAssetImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int insertSelective(StockOpnameUnregAssetImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    List<StockOpnameUnregAssetImgDTO> selectByExampleWithRowbounds(StockOpnameUnregAssetImgExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    List<StockOpnameUnregAssetImgDTO> selectByExample(StockOpnameUnregAssetImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    StockOpnameUnregAssetImgDTO selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    List<StockOpnameUnregAssetImgDTO> selectByHeaderKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int updateByExampleSelective(@Param("record") StockOpnameUnregAssetImg record, @Param("example") StockOpnameUnregAssetImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int updateByExample(@Param("record") StockOpnameUnregAssetImg record, @Param("example") StockOpnameUnregAssetImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int updateByPrimaryKeySelective(StockOpnameUnregAssetImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_RUNNER_HDR
     *
     * @mbggenerated Tue Mar 19 22:59:29 ICT 2013
     */
    int updateByPrimaryKey(StockOpnameUnregAssetImg record);
}