package co.id.fifgroup.systemworkflow.dao;

import co.id.fifgroup.systemworkflow.domain.ApprovalModelMappingHeader;
import co.id.fifgroup.systemworkflow.domain.ApprovalModelMappingHeaderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ApprovalModelMappingHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    int countByExample(ApprovalModelMappingHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    int deleteByPrimaryKey(Long modelMappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    int insert(ApprovalModelMappingHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    int insertSelective(ApprovalModelMappingHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    List<ApprovalModelMappingHeader> selectByExampleWithRowbounds(ApprovalModelMappingHeaderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    List<ApprovalModelMappingHeader> selectByExample(ApprovalModelMappingHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    ApprovalModelMappingHeader selectByPrimaryKey(Long modelMappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    int updateByExampleSelective(@Param("record") ApprovalModelMappingHeader record, @Param("example") ApprovalModelMappingHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    int updateByExample(@Param("record") ApprovalModelMappingHeader record, @Param("example") ApprovalModelMappingHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    int updateByPrimaryKeySelective(ApprovalModelMappingHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWF_AVM_MAPPING_HEADER
     *
     * @mbggenerated Thu Mar 07 10:10:26 ICT 2013
     */
    int updateByPrimaryKey(ApprovalModelMappingHeader record);
}