package co.id.fifgroup.systemadmin.domain;

import java.io.Serializable;
import java.util.Date;

public class ModuleErrorLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_MODULE_ERROR_LOGS.ERROR_LOG_ID
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    private Long errorLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_MODULE_ERROR_LOGS.TRX_ID
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    private Long trxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_MODULE_ERROR_LOGS.LOG_TIME
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    private Date logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_MODULE_ERROR_LOGS.MODULE_NAME
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_MODULE_ERROR_LOGS.ERROR_MESSAGE
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    private String errorMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_MODULE_ERROR_LOGS.ERROR_LOG_ID
     *
     * @return the value of SAM_MODULE_ERROR_LOGS.ERROR_LOG_ID
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    public Long getErrorLogId() {
        return errorLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_MODULE_ERROR_LOGS.ERROR_LOG_ID
     *
     * @param errorLogId the value for SAM_MODULE_ERROR_LOGS.ERROR_LOG_ID
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    public void setErrorLogId(Long errorLogId) {
        this.errorLogId = errorLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_MODULE_ERROR_LOGS.TRX_ID
     *
     * @return the value of SAM_MODULE_ERROR_LOGS.TRX_ID
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    public Long getTrxId() {
        return trxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_MODULE_ERROR_LOGS.TRX_ID
     *
     * @param trxId the value for SAM_MODULE_ERROR_LOGS.TRX_ID
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    public void setTrxId(Long trxId) {
        this.trxId = trxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_MODULE_ERROR_LOGS.LOG_TIME
     *
     * @return the value of SAM_MODULE_ERROR_LOGS.LOG_TIME
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_MODULE_ERROR_LOGS.LOG_TIME
     *
     * @param logTime the value for SAM_MODULE_ERROR_LOGS.LOG_TIME
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_MODULE_ERROR_LOGS.MODULE_NAME
     *
     * @return the value of SAM_MODULE_ERROR_LOGS.MODULE_NAME
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_MODULE_ERROR_LOGS.MODULE_NAME
     *
     * @param moduleName the value for SAM_MODULE_ERROR_LOGS.MODULE_NAME
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_MODULE_ERROR_LOGS.ERROR_MESSAGE
     *
     * @return the value of SAM_MODULE_ERROR_LOGS.ERROR_MESSAGE
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_MODULE_ERROR_LOGS.ERROR_MESSAGE
     *
     * @param errorMessage the value for SAM_MODULE_ERROR_LOGS.ERROR_MESSAGE
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage == null ? null : errorMessage.trim();
    }
}