package co.id.fifgroup.systemadmin.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskRequestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public TaskRequestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("TASK_REQUEST_ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("TASK_REQUEST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("TASK_REQUEST_ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("TASK_REQUEST_ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("TASK_REQUEST_ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TASK_REQUEST_ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("TASK_REQUEST_ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("TASK_REQUEST_ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("TASK_REQUEST_ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("TASK_REQUEST_ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("TASK_REQUEST_ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("TASK_REQUEST_ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdIsNull() {
            addCriterion("PARENT_REQUEST_ID is null");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdIsNotNull() {
            addCriterion("PARENT_REQUEST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdEqualTo(String value) {
            addCriterion("PARENT_REQUEST_ID =", value, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdNotEqualTo(String value) {
            addCriterion("PARENT_REQUEST_ID <>", value, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdGreaterThan(String value) {
            addCriterion("PARENT_REQUEST_ID >", value, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_REQUEST_ID >=", value, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdLessThan(String value) {
            addCriterion("PARENT_REQUEST_ID <", value, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdLessThanOrEqualTo(String value) {
            addCriterion("PARENT_REQUEST_ID <=", value, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdLike(String value) {
            addCriterion("PARENT_REQUEST_ID like", value, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdNotLike(String value) {
            addCriterion("PARENT_REQUEST_ID not like", value, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdIn(List<String> values) {
            addCriterion("PARENT_REQUEST_ID in", values, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdNotIn(List<String> values) {
            addCriterion("PARENT_REQUEST_ID not in", values, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdBetween(String value1, String value2) {
            addCriterion("PARENT_REQUEST_ID between", value1, value2, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdNotBetween(String value1, String value2) {
            addCriterion("PARENT_REQUEST_ID not between", value1, value2, "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdIsNull() {
            addCriterion("TASK_RUNNER_ID is null");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdIsNotNull() {
            addCriterion("TASK_RUNNER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdEqualTo(Long value) {
            addCriterion("TASK_RUNNER_ID =", value, "taskRunnerId");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdNotEqualTo(Long value) {
            addCriterion("TASK_RUNNER_ID <>", value, "taskRunnerId");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdGreaterThan(Long value) {
            addCriterion("TASK_RUNNER_ID >", value, "taskRunnerId");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TASK_RUNNER_ID >=", value, "taskRunnerId");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdLessThan(Long value) {
            addCriterion("TASK_RUNNER_ID <", value, "taskRunnerId");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdLessThanOrEqualTo(Long value) {
            addCriterion("TASK_RUNNER_ID <=", value, "taskRunnerId");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdIn(List<Long> values) {
            addCriterion("TASK_RUNNER_ID in", values, "taskRunnerId");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdNotIn(List<Long> values) {
            addCriterion("TASK_RUNNER_ID not in", values, "taskRunnerId");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdBetween(Long value1, Long value2) {
            addCriterion("TASK_RUNNER_ID between", value1, value2, "taskRunnerId");
            return (Criteria) this;
        }

        public Criteria andTaskRunnerIdNotBetween(Long value1, Long value2) {
            addCriterion("TASK_RUNNER_ID not between", value1, value2, "taskRunnerId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("TASK_ID is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("TASK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Long value) {
            addCriterion("TASK_ID =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Long value) {
            addCriterion("TASK_ID <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Long value) {
            addCriterion("TASK_ID >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TASK_ID >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Long value) {
            addCriterion("TASK_ID <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Long value) {
            addCriterion("TASK_ID <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Long> values) {
            addCriterion("TASK_ID in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Long> values) {
            addCriterion("TASK_ID not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Long value1, Long value2) {
            addCriterion("TASK_ID between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Long value1, Long value2) {
            addCriterion("TASK_ID not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedIsNull() {
            addCriterion("DATE_SUBMITTED is null");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedIsNotNull() {
            addCriterion("DATE_SUBMITTED is not null");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedEqualTo(Date value) {
            addCriterion("DATE_SUBMITTED =", value, "dateSubmitted");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedNotEqualTo(Date value) {
            addCriterion("DATE_SUBMITTED <>", value, "dateSubmitted");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedGreaterThan(Date value) {
            addCriterion("DATE_SUBMITTED >", value, "dateSubmitted");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedGreaterThanOrEqualTo(Date value) {
            addCriterion("DATE_SUBMITTED >=", value, "dateSubmitted");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedLessThan(Date value) {
            addCriterion("DATE_SUBMITTED <", value, "dateSubmitted");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedLessThanOrEqualTo(Date value) {
            addCriterion("DATE_SUBMITTED <=", value, "dateSubmitted");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedIn(List<Date> values) {
            addCriterion("DATE_SUBMITTED in", values, "dateSubmitted");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedNotIn(List<Date> values) {
            addCriterion("DATE_SUBMITTED not in", values, "dateSubmitted");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedBetween(Date value1, Date value2) {
            addCriterion("DATE_SUBMITTED between", value1, value2, "dateSubmitted");
            return (Criteria) this;
        }

        public Criteria andDateSubmittedNotBetween(Date value1, Date value2) {
            addCriterion("DATE_SUBMITTED not between", value1, value2, "dateSubmitted");
            return (Criteria) this;
        }

        public Criteria andDateCompletedIsNull() {
            addCriterion("DATE_COMPLETED is null");
            return (Criteria) this;
        }

        public Criteria andDateCompletedIsNotNull() {
            addCriterion("DATE_COMPLETED is not null");
            return (Criteria) this;
        }

        public Criteria andDateCompletedEqualTo(Date value) {
            addCriterion("DATE_COMPLETED =", value, "dateCompleted");
            return (Criteria) this;
        }

        public Criteria andDateCompletedNotEqualTo(Date value) {
            addCriterion("DATE_COMPLETED <>", value, "dateCompleted");
            return (Criteria) this;
        }

        public Criteria andDateCompletedGreaterThan(Date value) {
            addCriterion("DATE_COMPLETED >", value, "dateCompleted");
            return (Criteria) this;
        }

        public Criteria andDateCompletedGreaterThanOrEqualTo(Date value) {
            addCriterion("DATE_COMPLETED >=", value, "dateCompleted");
            return (Criteria) this;
        }

        public Criteria andDateCompletedLessThan(Date value) {
            addCriterion("DATE_COMPLETED <", value, "dateCompleted");
            return (Criteria) this;
        }

        public Criteria andDateCompletedLessThanOrEqualTo(Date value) {
            addCriterion("DATE_COMPLETED <=", value, "dateCompleted");
            return (Criteria) this;
        }

        public Criteria andDateCompletedIn(List<Date> values) {
            addCriterion("DATE_COMPLETED in", values, "dateCompleted");
            return (Criteria) this;
        }

        public Criteria andDateCompletedNotIn(List<Date> values) {
            addCriterion("DATE_COMPLETED not in", values, "dateCompleted");
            return (Criteria) this;
        }

        public Criteria andDateCompletedBetween(Date value1, Date value2) {
            addCriterion("DATE_COMPLETED between", value1, value2, "dateCompleted");
            return (Criteria) this;
        }

        public Criteria andDateCompletedNotBetween(Date value1, Date value2) {
            addCriterion("DATE_COMPLETED not between", value1, value2, "dateCompleted");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeIsNull() {
            addCriterion("SCHEDULE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeIsNotNull() {
            addCriterion("SCHEDULE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeEqualTo(String value) {
            addCriterion("SCHEDULE_TYPE =", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotEqualTo(String value) {
            addCriterion("SCHEDULE_TYPE <>", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeGreaterThan(String value) {
            addCriterion("SCHEDULE_TYPE >", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_TYPE >=", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeLessThan(String value) {
            addCriterion("SCHEDULE_TYPE <", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeLessThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_TYPE <=", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeLike(String value) {
            addCriterion("SCHEDULE_TYPE like", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotLike(String value) {
            addCriterion("SCHEDULE_TYPE not like", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeIn(List<String> values) {
            addCriterion("SCHEDULE_TYPE in", values, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotIn(List<String> values) {
            addCriterion("SCHEDULE_TYPE not in", values, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeBetween(String value1, String value2) {
            addCriterion("SCHEDULE_TYPE between", value1, value2, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotBetween(String value1, String value2) {
            addCriterion("SCHEDULE_TYPE not between", value1, value2, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andOutputFormatIsNull() {
            addCriterion("OUTPUT_FORMAT is null");
            return (Criteria) this;
        }

        public Criteria andOutputFormatIsNotNull() {
            addCriterion("OUTPUT_FORMAT is not null");
            return (Criteria) this;
        }

        public Criteria andOutputFormatEqualTo(String value) {
            addCriterion("OUTPUT_FORMAT =", value, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatNotEqualTo(String value) {
            addCriterion("OUTPUT_FORMAT <>", value, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatGreaterThan(String value) {
            addCriterion("OUTPUT_FORMAT >", value, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatGreaterThanOrEqualTo(String value) {
            addCriterion("OUTPUT_FORMAT >=", value, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatLessThan(String value) {
            addCriterion("OUTPUT_FORMAT <", value, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatLessThanOrEqualTo(String value) {
            addCriterion("OUTPUT_FORMAT <=", value, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatLike(String value) {
            addCriterion("OUTPUT_FORMAT like", value, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatNotLike(String value) {
            addCriterion("OUTPUT_FORMAT not like", value, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatIn(List<String> values) {
            addCriterion("OUTPUT_FORMAT in", values, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatNotIn(List<String> values) {
            addCriterion("OUTPUT_FORMAT not in", values, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatBetween(String value1, String value2) {
            addCriterion("OUTPUT_FORMAT between", value1, value2, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andOutputFormatNotBetween(String value1, String value2) {
            addCriterion("OUTPUT_FORMAT not between", value1, value2, "outputFormat");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("START_TIME =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("START_TIME <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("START_TIME >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("START_TIME >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("START_TIME <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("START_TIME <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("START_TIME in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("START_TIME not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("START_TIME between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("START_TIME not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedIsNull() {
            addCriterion("AFTER_COMPLETED is null");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedIsNotNull() {
            addCriterion("AFTER_COMPLETED is not null");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedEqualTo(String value) {
            addCriterion("AFTER_COMPLETED =", value, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedNotEqualTo(String value) {
            addCriterion("AFTER_COMPLETED <>", value, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedGreaterThan(String value) {
            addCriterion("AFTER_COMPLETED >", value, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedGreaterThanOrEqualTo(String value) {
            addCriterion("AFTER_COMPLETED >=", value, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedLessThan(String value) {
            addCriterion("AFTER_COMPLETED <", value, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedLessThanOrEqualTo(String value) {
            addCriterion("AFTER_COMPLETED <=", value, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedLike(String value) {
            addCriterion("AFTER_COMPLETED like", value, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedNotLike(String value) {
            addCriterion("AFTER_COMPLETED not like", value, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedIn(List<String> values) {
            addCriterion("AFTER_COMPLETED in", values, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedNotIn(List<String> values) {
            addCriterion("AFTER_COMPLETED not in", values, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedBetween(String value1, String value2) {
            addCriterion("AFTER_COMPLETED between", value1, value2, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedNotBetween(String value1, String value2) {
            addCriterion("AFTER_COMPLETED not between", value1, value2, "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andEndTypeIsNull() {
            addCriterion("END_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andEndTypeIsNotNull() {
            addCriterion("END_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andEndTypeEqualTo(String value) {
            addCriterion("END_TYPE =", value, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeNotEqualTo(String value) {
            addCriterion("END_TYPE <>", value, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeGreaterThan(String value) {
            addCriterion("END_TYPE >", value, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeGreaterThanOrEqualTo(String value) {
            addCriterion("END_TYPE >=", value, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeLessThan(String value) {
            addCriterion("END_TYPE <", value, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeLessThanOrEqualTo(String value) {
            addCriterion("END_TYPE <=", value, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeLike(String value) {
            addCriterion("END_TYPE like", value, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeNotLike(String value) {
            addCriterion("END_TYPE not like", value, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeIn(List<String> values) {
            addCriterion("END_TYPE in", values, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeNotIn(List<String> values) {
            addCriterion("END_TYPE not in", values, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeBetween(String value1, String value2) {
            addCriterion("END_TYPE between", value1, value2, "endType");
            return (Criteria) this;
        }

        public Criteria andEndTypeNotBetween(String value1, String value2) {
            addCriterion("END_TYPE not between", value1, value2, "endType");
            return (Criteria) this;
        }

        public Criteria andEndByDateIsNull() {
            addCriterion("END_BY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEndByDateIsNotNull() {
            addCriterion("END_BY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEndByDateEqualTo(Date value) {
            addCriterion("END_BY_DATE =", value, "endByDate");
            return (Criteria) this;
        }

        public Criteria andEndByDateNotEqualTo(Date value) {
            addCriterion("END_BY_DATE <>", value, "endByDate");
            return (Criteria) this;
        }

        public Criteria andEndByDateGreaterThan(Date value) {
            addCriterion("END_BY_DATE >", value, "endByDate");
            return (Criteria) this;
        }

        public Criteria andEndByDateGreaterThanOrEqualTo(Date value) {
            addCriterion("END_BY_DATE >=", value, "endByDate");
            return (Criteria) this;
        }

        public Criteria andEndByDateLessThan(Date value) {
            addCriterion("END_BY_DATE <", value, "endByDate");
            return (Criteria) this;
        }

        public Criteria andEndByDateLessThanOrEqualTo(Date value) {
            addCriterion("END_BY_DATE <=", value, "endByDate");
            return (Criteria) this;
        }

        public Criteria andEndByDateIn(List<Date> values) {
            addCriterion("END_BY_DATE in", values, "endByDate");
            return (Criteria) this;
        }

        public Criteria andEndByDateNotIn(List<Date> values) {
            addCriterion("END_BY_DATE not in", values, "endByDate");
            return (Criteria) this;
        }

        public Criteria andEndByDateBetween(Date value1, Date value2) {
            addCriterion("END_BY_DATE between", value1, value2, "endByDate");
            return (Criteria) this;
        }

        public Criteria andEndByDateNotBetween(Date value1, Date value2) {
            addCriterion("END_BY_DATE not between", value1, value2, "endByDate");
            return (Criteria) this;
        }

        public Criteria andPrinterIdIsNull() {
            addCriterion("PRINTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andPrinterIdIsNotNull() {
            addCriterion("PRINTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPrinterIdEqualTo(Long value) {
            addCriterion("PRINTER_ID =", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdNotEqualTo(Long value) {
            addCriterion("PRINTER_ID <>", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdGreaterThan(Long value) {
            addCriterion("PRINTER_ID >", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PRINTER_ID >=", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdLessThan(Long value) {
            addCriterion("PRINTER_ID <", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdLessThanOrEqualTo(Long value) {
            addCriterion("PRINTER_ID <=", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdIn(List<Long> values) {
            addCriterion("PRINTER_ID in", values, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdNotIn(List<Long> values) {
            addCriterion("PRINTER_ID not in", values, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdBetween(Long value1, Long value2) {
            addCriterion("PRINTER_ID between", value1, value2, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdNotBetween(Long value1, Long value2) {
            addCriterion("PRINTER_ID not between", value1, value2, "printerId");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceIsNull() {
            addCriterion("END_AFTER_OCCURENCE is null");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceIsNotNull() {
            addCriterion("END_AFTER_OCCURENCE is not null");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceEqualTo(Integer value) {
            addCriterion("END_AFTER_OCCURENCE =", value, "endAfterOccurence");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceNotEqualTo(Integer value) {
            addCriterion("END_AFTER_OCCURENCE <>", value, "endAfterOccurence");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceGreaterThan(Integer value) {
            addCriterion("END_AFTER_OCCURENCE >", value, "endAfterOccurence");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("END_AFTER_OCCURENCE >=", value, "endAfterOccurence");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceLessThan(Integer value) {
            addCriterion("END_AFTER_OCCURENCE <", value, "endAfterOccurence");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceLessThanOrEqualTo(Integer value) {
            addCriterion("END_AFTER_OCCURENCE <=", value, "endAfterOccurence");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceIn(List<Integer> values) {
            addCriterion("END_AFTER_OCCURENCE in", values, "endAfterOccurence");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceNotIn(List<Integer> values) {
            addCriterion("END_AFTER_OCCURENCE not in", values, "endAfterOccurence");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceBetween(Integer value1, Integer value2) {
            addCriterion("END_AFTER_OCCURENCE between", value1, value2, "endAfterOccurence");
            return (Criteria) this;
        }

        public Criteria andEndAfterOccurenceNotBetween(Integer value1, Integer value2) {
            addCriterion("END_AFTER_OCCURENCE not between", value1, value2, "endAfterOccurence");
            return (Criteria) this;
        }

        public Criteria andDailyPatternIsNull() {
            addCriterion("DAILY_PATTERN is null");
            return (Criteria) this;
        }

        public Criteria andDailyPatternIsNotNull() {
            addCriterion("DAILY_PATTERN is not null");
            return (Criteria) this;
        }

        public Criteria andDailyPatternEqualTo(String value) {
            addCriterion("DAILY_PATTERN =", value, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternNotEqualTo(String value) {
            addCriterion("DAILY_PATTERN <>", value, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternGreaterThan(String value) {
            addCriterion("DAILY_PATTERN >", value, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternGreaterThanOrEqualTo(String value) {
            addCriterion("DAILY_PATTERN >=", value, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternLessThan(String value) {
            addCriterion("DAILY_PATTERN <", value, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternLessThanOrEqualTo(String value) {
            addCriterion("DAILY_PATTERN <=", value, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternLike(String value) {
            addCriterion("DAILY_PATTERN like", value, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternNotLike(String value) {
            addCriterion("DAILY_PATTERN not like", value, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternIn(List<String> values) {
            addCriterion("DAILY_PATTERN in", values, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternNotIn(List<String> values) {
            addCriterion("DAILY_PATTERN not in", values, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternBetween(String value1, String value2) {
            addCriterion("DAILY_PATTERN between", value1, value2, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andDailyPatternNotBetween(String value1, String value2) {
            addCriterion("DAILY_PATTERN not between", value1, value2, "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternIsNull() {
            addCriterion("MONTHLY_PATTERN is null");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternIsNotNull() {
            addCriterion("MONTHLY_PATTERN is not null");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternEqualTo(String value) {
            addCriterion("MONTHLY_PATTERN =", value, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternNotEqualTo(String value) {
            addCriterion("MONTHLY_PATTERN <>", value, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternGreaterThan(String value) {
            addCriterion("MONTHLY_PATTERN >", value, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternGreaterThanOrEqualTo(String value) {
            addCriterion("MONTHLY_PATTERN >=", value, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternLessThan(String value) {
            addCriterion("MONTHLY_PATTERN <", value, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternLessThanOrEqualTo(String value) {
            addCriterion("MONTHLY_PATTERN <=", value, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternLike(String value) {
            addCriterion("MONTHLY_PATTERN like", value, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternNotLike(String value) {
            addCriterion("MONTHLY_PATTERN not like", value, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternIn(List<String> values) {
            addCriterion("MONTHLY_PATTERN in", values, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternNotIn(List<String> values) {
            addCriterion("MONTHLY_PATTERN not in", values, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternBetween(String value1, String value2) {
            addCriterion("MONTHLY_PATTERN between", value1, value2, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternNotBetween(String value1, String value2) {
            addCriterion("MONTHLY_PATTERN not between", value1, value2, "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternIsNull() {
            addCriterion("YEARLY_PATTERN is null");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternIsNotNull() {
            addCriterion("YEARLY_PATTERN is not null");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternEqualTo(String value) {
            addCriterion("YEARLY_PATTERN =", value, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternNotEqualTo(String value) {
            addCriterion("YEARLY_PATTERN <>", value, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternGreaterThan(String value) {
            addCriterion("YEARLY_PATTERN >", value, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternGreaterThanOrEqualTo(String value) {
            addCriterion("YEARLY_PATTERN >=", value, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternLessThan(String value) {
            addCriterion("YEARLY_PATTERN <", value, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternLessThanOrEqualTo(String value) {
            addCriterion("YEARLY_PATTERN <=", value, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternLike(String value) {
            addCriterion("YEARLY_PATTERN like", value, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternNotLike(String value) {
            addCriterion("YEARLY_PATTERN not like", value, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternIn(List<String> values) {
            addCriterion("YEARLY_PATTERN in", values, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternNotIn(List<String> values) {
            addCriterion("YEARLY_PATTERN not in", values, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternBetween(String value1, String value2) {
            addCriterion("YEARLY_PATTERN between", value1, value2, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternNotBetween(String value1, String value2) {
            addCriterion("YEARLY_PATTERN not between", value1, value2, "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andTotalDayIsNull() {
            addCriterion("TOTAL_DAY is null");
            return (Criteria) this;
        }

        public Criteria andTotalDayIsNotNull() {
            addCriterion("TOTAL_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andTotalDayEqualTo(Integer value) {
            addCriterion("TOTAL_DAY =", value, "totalDay");
            return (Criteria) this;
        }

        public Criteria andTotalDayNotEqualTo(Integer value) {
            addCriterion("TOTAL_DAY <>", value, "totalDay");
            return (Criteria) this;
        }

        public Criteria andTotalDayGreaterThan(Integer value) {
            addCriterion("TOTAL_DAY >", value, "totalDay");
            return (Criteria) this;
        }

        public Criteria andTotalDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_DAY >=", value, "totalDay");
            return (Criteria) this;
        }

        public Criteria andTotalDayLessThan(Integer value) {
            addCriterion("TOTAL_DAY <", value, "totalDay");
            return (Criteria) this;
        }

        public Criteria andTotalDayLessThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_DAY <=", value, "totalDay");
            return (Criteria) this;
        }

        public Criteria andTotalDayIn(List<Integer> values) {
            addCriterion("TOTAL_DAY in", values, "totalDay");
            return (Criteria) this;
        }

        public Criteria andTotalDayNotIn(List<Integer> values) {
            addCriterion("TOTAL_DAY not in", values, "totalDay");
            return (Criteria) this;
        }

        public Criteria andTotalDayBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_DAY between", value1, value2, "totalDay");
            return (Criteria) this;
        }

        public Criteria andTotalDayNotBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_DAY not between", value1, value2, "totalDay");
            return (Criteria) this;
        }

        public Criteria andRecurEveryIsNull() {
            addCriterion("RECUR_EVERY is null");
            return (Criteria) this;
        }

        public Criteria andRecurEveryIsNotNull() {
            addCriterion("RECUR_EVERY is not null");
            return (Criteria) this;
        }

        public Criteria andRecurEveryEqualTo(Integer value) {
            addCriterion("RECUR_EVERY =", value, "recurEvery");
            return (Criteria) this;
        }

        public Criteria andRecurEveryNotEqualTo(Integer value) {
            addCriterion("RECUR_EVERY <>", value, "recurEvery");
            return (Criteria) this;
        }

        public Criteria andRecurEveryGreaterThan(Integer value) {
            addCriterion("RECUR_EVERY >", value, "recurEvery");
            return (Criteria) this;
        }

        public Criteria andRecurEveryGreaterThanOrEqualTo(Integer value) {
            addCriterion("RECUR_EVERY >=", value, "recurEvery");
            return (Criteria) this;
        }

        public Criteria andRecurEveryLessThan(Integer value) {
            addCriterion("RECUR_EVERY <", value, "recurEvery");
            return (Criteria) this;
        }

        public Criteria andRecurEveryLessThanOrEqualTo(Integer value) {
            addCriterion("RECUR_EVERY <=", value, "recurEvery");
            return (Criteria) this;
        }

        public Criteria andRecurEveryIn(List<Integer> values) {
            addCriterion("RECUR_EVERY in", values, "recurEvery");
            return (Criteria) this;
        }

        public Criteria andRecurEveryNotIn(List<Integer> values) {
            addCriterion("RECUR_EVERY not in", values, "recurEvery");
            return (Criteria) this;
        }

        public Criteria andRecurEveryBetween(Integer value1, Integer value2) {
            addCriterion("RECUR_EVERY between", value1, value2, "recurEvery");
            return (Criteria) this;
        }

        public Criteria andRecurEveryNotBetween(Integer value1, Integer value2) {
            addCriterion("RECUR_EVERY not between", value1, value2, "recurEvery");
            return (Criteria) this;
        }

        public Criteria andRecurOnIsNull() {
            addCriterion("RECUR_ON is null");
            return (Criteria) this;
        }

        public Criteria andRecurOnIsNotNull() {
            addCriterion("RECUR_ON is not null");
            return (Criteria) this;
        }

        public Criteria andRecurOnEqualTo(String value) {
            addCriterion("RECUR_ON =", value, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnNotEqualTo(String value) {
            addCriterion("RECUR_ON <>", value, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnGreaterThan(String value) {
            addCriterion("RECUR_ON >", value, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnGreaterThanOrEqualTo(String value) {
            addCriterion("RECUR_ON >=", value, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnLessThan(String value) {
            addCriterion("RECUR_ON <", value, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnLessThanOrEqualTo(String value) {
            addCriterion("RECUR_ON <=", value, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnLike(String value) {
            addCriterion("RECUR_ON like", value, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnNotLike(String value) {
            addCriterion("RECUR_ON not like", value, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnIn(List<String> values) {
            addCriterion("RECUR_ON in", values, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnNotIn(List<String> values) {
            addCriterion("RECUR_ON not in", values, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnBetween(String value1, String value2) {
            addCriterion("RECUR_ON between", value1, value2, "recurOn");
            return (Criteria) this;
        }

        public Criteria andRecurOnNotBetween(String value1, String value2) {
            addCriterion("RECUR_ON not between", value1, value2, "recurOn");
            return (Criteria) this;
        }

        public Criteria andDayNumIsNull() {
            addCriterion("DAY_NUM is null");
            return (Criteria) this;
        }

        public Criteria andDayNumIsNotNull() {
            addCriterion("DAY_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andDayNumEqualTo(Integer value) {
            addCriterion("DAY_NUM =", value, "dayNum");
            return (Criteria) this;
        }

        public Criteria andDayNumNotEqualTo(Integer value) {
            addCriterion("DAY_NUM <>", value, "dayNum");
            return (Criteria) this;
        }

        public Criteria andDayNumGreaterThan(Integer value) {
            addCriterion("DAY_NUM >", value, "dayNum");
            return (Criteria) this;
        }

        public Criteria andDayNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("DAY_NUM >=", value, "dayNum");
            return (Criteria) this;
        }

        public Criteria andDayNumLessThan(Integer value) {
            addCriterion("DAY_NUM <", value, "dayNum");
            return (Criteria) this;
        }

        public Criteria andDayNumLessThanOrEqualTo(Integer value) {
            addCriterion("DAY_NUM <=", value, "dayNum");
            return (Criteria) this;
        }

        public Criteria andDayNumIn(List<Integer> values) {
            addCriterion("DAY_NUM in", values, "dayNum");
            return (Criteria) this;
        }

        public Criteria andDayNumNotIn(List<Integer> values) {
            addCriterion("DAY_NUM not in", values, "dayNum");
            return (Criteria) this;
        }

        public Criteria andDayNumBetween(Integer value1, Integer value2) {
            addCriterion("DAY_NUM between", value1, value2, "dayNum");
            return (Criteria) this;
        }

        public Criteria andDayNumNotBetween(Integer value1, Integer value2) {
            addCriterion("DAY_NUM not between", value1, value2, "dayNum");
            return (Criteria) this;
        }

        public Criteria andTotalMonthIsNull() {
            addCriterion("TOTAL_MONTH is null");
            return (Criteria) this;
        }

        public Criteria andTotalMonthIsNotNull() {
            addCriterion("TOTAL_MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andTotalMonthEqualTo(Integer value) {
            addCriterion("TOTAL_MONTH =", value, "totalMonth");
            return (Criteria) this;
        }

        public Criteria andTotalMonthNotEqualTo(Integer value) {
            addCriterion("TOTAL_MONTH <>", value, "totalMonth");
            return (Criteria) this;
        }

        public Criteria andTotalMonthGreaterThan(Integer value) {
            addCriterion("TOTAL_MONTH >", value, "totalMonth");
            return (Criteria) this;
        }

        public Criteria andTotalMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_MONTH >=", value, "totalMonth");
            return (Criteria) this;
        }

        public Criteria andTotalMonthLessThan(Integer value) {
            addCriterion("TOTAL_MONTH <", value, "totalMonth");
            return (Criteria) this;
        }

        public Criteria andTotalMonthLessThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_MONTH <=", value, "totalMonth");
            return (Criteria) this;
        }

        public Criteria andTotalMonthIn(List<Integer> values) {
            addCriterion("TOTAL_MONTH in", values, "totalMonth");
            return (Criteria) this;
        }

        public Criteria andTotalMonthNotIn(List<Integer> values) {
            addCriterion("TOTAL_MONTH not in", values, "totalMonth");
            return (Criteria) this;
        }

        public Criteria andTotalMonthBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_MONTH between", value1, value2, "totalMonth");
            return (Criteria) this;
        }

        public Criteria andTotalMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_MONTH not between", value1, value2, "totalMonth");
            return (Criteria) this;
        }

        public Criteria andDayNameIsNull() {
            addCriterion("DAY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDayNameIsNotNull() {
            addCriterion("DAY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDayNameEqualTo(String value) {
            addCriterion("DAY_NAME =", value, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameNotEqualTo(String value) {
            addCriterion("DAY_NAME <>", value, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameGreaterThan(String value) {
            addCriterion("DAY_NAME >", value, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameGreaterThanOrEqualTo(String value) {
            addCriterion("DAY_NAME >=", value, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameLessThan(String value) {
            addCriterion("DAY_NAME <", value, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameLessThanOrEqualTo(String value) {
            addCriterion("DAY_NAME <=", value, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameLike(String value) {
            addCriterion("DAY_NAME like", value, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameNotLike(String value) {
            addCriterion("DAY_NAME not like", value, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameIn(List<String> values) {
            addCriterion("DAY_NAME in", values, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameNotIn(List<String> values) {
            addCriterion("DAY_NAME not in", values, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameBetween(String value1, String value2) {
            addCriterion("DAY_NAME between", value1, value2, "dayName");
            return (Criteria) this;
        }

        public Criteria andDayNameNotBetween(String value1, String value2) {
            addCriterion("DAY_NAME not between", value1, value2, "dayName");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeIsNull() {
            addCriterion("SEQUENCE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeIsNotNull() {
            addCriterion("SEQUENCE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeEqualTo(String value) {
            addCriterion("SEQUENCE_TYPE =", value, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeNotEqualTo(String value) {
            addCriterion("SEQUENCE_TYPE <>", value, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeGreaterThan(String value) {
            addCriterion("SEQUENCE_TYPE >", value, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SEQUENCE_TYPE >=", value, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeLessThan(String value) {
            addCriterion("SEQUENCE_TYPE <", value, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeLessThanOrEqualTo(String value) {
            addCriterion("SEQUENCE_TYPE <=", value, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeLike(String value) {
            addCriterion("SEQUENCE_TYPE like", value, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeNotLike(String value) {
            addCriterion("SEQUENCE_TYPE not like", value, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeIn(List<String> values) {
            addCriterion("SEQUENCE_TYPE in", values, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeNotIn(List<String> values) {
            addCriterion("SEQUENCE_TYPE not in", values, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeBetween(String value1, String value2) {
            addCriterion("SEQUENCE_TYPE between", value1, value2, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeNotBetween(String value1, String value2) {
            addCriterion("SEQUENCE_TYPE not between", value1, value2, "sequenceType");
            return (Criteria) this;
        }

        public Criteria andMonthNameIsNull() {
            addCriterion("MONTH_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMonthNameIsNotNull() {
            addCriterion("MONTH_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMonthNameEqualTo(String value) {
            addCriterion("MONTH_NAME =", value, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameNotEqualTo(String value) {
            addCriterion("MONTH_NAME <>", value, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameGreaterThan(String value) {
            addCriterion("MONTH_NAME >", value, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameGreaterThanOrEqualTo(String value) {
            addCriterion("MONTH_NAME >=", value, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameLessThan(String value) {
            addCriterion("MONTH_NAME <", value, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameLessThanOrEqualTo(String value) {
            addCriterion("MONTH_NAME <=", value, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameLike(String value) {
            addCriterion("MONTH_NAME like", value, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameNotLike(String value) {
            addCriterion("MONTH_NAME not like", value, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameIn(List<String> values) {
            addCriterion("MONTH_NAME in", values, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameNotIn(List<String> values) {
            addCriterion("MONTH_NAME not in", values, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameBetween(String value1, String value2) {
            addCriterion("MONTH_NAME between", value1, value2, "monthName");
            return (Criteria) this;
        }

        public Criteria andMonthNameNotBetween(String value1, String value2) {
            addCriterion("MONTH_NAME not between", value1, value2, "monthName");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursIsNull() {
            addCriterion("EXECUTION_HOURS is null");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursIsNotNull() {
            addCriterion("EXECUTION_HOURS is not null");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursEqualTo(Date value) {
            addCriterion("EXECUTION_HOURS =", value, "executionHours");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursNotEqualTo(Date value) {
            addCriterion("EXECUTION_HOURS <>", value, "executionHours");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursGreaterThan(Date value) {
            addCriterion("EXECUTION_HOURS >", value, "executionHours");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursGreaterThanOrEqualTo(Date value) {
            addCriterion("EXECUTION_HOURS >=", value, "executionHours");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursLessThan(Date value) {
            addCriterion("EXECUTION_HOURS <", value, "executionHours");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursLessThanOrEqualTo(Date value) {
            addCriterion("EXECUTION_HOURS <=", value, "executionHours");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursIn(List<Date> values) {
            addCriterion("EXECUTION_HOURS in", values, "executionHours");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursNotIn(List<Date> values) {
            addCriterion("EXECUTION_HOURS not in", values, "executionHours");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursBetween(Date value1, Date value2) {
            addCriterion("EXECUTION_HOURS between", value1, value2, "executionHours");
            return (Criteria) this;
        }

        public Criteria andExecutionHoursNotBetween(Date value1, Date value2) {
            addCriterion("EXECUTION_HOURS not between", value1, value2, "executionHours");
            return (Criteria) this;
        }

        public Criteria andCronExpressionIsNull() {
            addCriterion("CRON_EXPRESSION is null");
            return (Criteria) this;
        }

        public Criteria andCronExpressionIsNotNull() {
            addCriterion("CRON_EXPRESSION is not null");
            return (Criteria) this;
        }

        public Criteria andCronExpressionEqualTo(String value) {
            addCriterion("CRON_EXPRESSION =", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotEqualTo(String value) {
            addCriterion("CRON_EXPRESSION <>", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionGreaterThan(String value) {
            addCriterion("CRON_EXPRESSION >", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionGreaterThanOrEqualTo(String value) {
            addCriterion("CRON_EXPRESSION >=", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionLessThan(String value) {
            addCriterion("CRON_EXPRESSION <", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionLessThanOrEqualTo(String value) {
            addCriterion("CRON_EXPRESSION <=", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionLike(String value) {
            addCriterion("CRON_EXPRESSION like", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotLike(String value) {
            addCriterion("CRON_EXPRESSION not like", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionIn(List<String> values) {
            addCriterion("CRON_EXPRESSION in", values, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotIn(List<String> values) {
            addCriterion("CRON_EXPRESSION not in", values, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionBetween(String value1, String value2) {
            addCriterion("CRON_EXPRESSION between", value1, value2, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotBetween(String value1, String value2) {
            addCriterion("CRON_EXPRESSION not between", value1, value2, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Long value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Long value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Long value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Long value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Long value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Long> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Long> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Long value1, Long value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Long value1, Long value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNull() {
            addCriterion("CREATION_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNotNull() {
            addCriterion("CREATION_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDateEqualTo(Date value) {
            addCriterion("CREATION_DATE =", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotEqualTo(Date value) {
            addCriterion("CREATION_DATE <>", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThan(Date value) {
            addCriterion("CREATION_DATE >", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATION_DATE >=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThan(Date value) {
            addCriterion("CREATION_DATE <", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATION_DATE <=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateIn(List<Date> values) {
            addCriterion("CREATION_DATE in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotIn(List<Date> values) {
            addCriterion("CREATION_DATE not in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateBetween(Date value1, Date value2) {
            addCriterion("CREATION_DATE between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATION_DATE not between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNull() {
            addCriterion("LAST_UPDATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNotNull() {
            addCriterion("LAST_UPDATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY =", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY <>", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThan(Long value) {
            addCriterion("LAST_UPDATED_BY >", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY >=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThan(Long value) {
            addCriterion("LAST_UPDATED_BY <", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThanOrEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY <=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIn(List<Long> values) {
            addCriterion("LAST_UPDATED_BY in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotIn(List<Long> values) {
            addCriterion("LAST_UPDATED_BY not in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByBetween(Long value1, Long value2) {
            addCriterion("LAST_UPDATED_BY between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotBetween(Long value1, Long value2) {
            addCriterion("LAST_UPDATED_BY not between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andParentRequestIdLikeInsensitive(String value) {
            addCriterion("upper(PARENT_REQUEST_ID) like", value.toUpperCase(), "parentRequestId");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeLikeInsensitive(String value) {
            addCriterion("upper(SCHEDULE_TYPE) like", value.toUpperCase(), "scheduleType");
            return (Criteria) this;
        }

        public Criteria andOutputFormatLikeInsensitive(String value) {
            addCriterion("upper(OUTPUT_FORMAT) like", value.toUpperCase(), "outputFormat");
            return (Criteria) this;
        }

        public Criteria andAfterCompletedLikeInsensitive(String value) {
            addCriterion("upper(AFTER_COMPLETED) like", value.toUpperCase(), "afterCompleted");
            return (Criteria) this;
        }

        public Criteria andEndTypeLikeInsensitive(String value) {
            addCriterion("upper(END_TYPE) like", value.toUpperCase(), "endType");
            return (Criteria) this;
        }

        public Criteria andDailyPatternLikeInsensitive(String value) {
            addCriterion("upper(DAILY_PATTERN) like", value.toUpperCase(), "dailyPattern");
            return (Criteria) this;
        }

        public Criteria andMonthlyPatternLikeInsensitive(String value) {
            addCriterion("upper(MONTHLY_PATTERN) like", value.toUpperCase(), "monthlyPattern");
            return (Criteria) this;
        }

        public Criteria andYearlyPatternLikeInsensitive(String value) {
            addCriterion("upper(YEARLY_PATTERN) like", value.toUpperCase(), "yearlyPattern");
            return (Criteria) this;
        }

        public Criteria andRecurOnLikeInsensitive(String value) {
            addCriterion("upper(RECUR_ON) like", value.toUpperCase(), "recurOn");
            return (Criteria) this;
        }

        public Criteria andDayNameLikeInsensitive(String value) {
            addCriterion("upper(DAY_NAME) like", value.toUpperCase(), "dayName");
            return (Criteria) this;
        }

        public Criteria andSequenceTypeLikeInsensitive(String value) {
            addCriterion("upper(SEQUENCE_TYPE) like", value.toUpperCase(), "sequenceType");
            return (Criteria) this;
        }

        public Criteria andMonthNameLikeInsensitive(String value) {
            addCriterion("upper(MONTH_NAME) like", value.toUpperCase(), "monthName");
            return (Criteria) this;
        }

        public Criteria andCronExpressionLikeInsensitive(String value) {
            addCriterion("upper(CRON_EXPRESSION) like", value.toUpperCase(), "cronExpression");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 13 16:05:34 ICT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}