package co.id.fifgroup.systemadmin.domain;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_USERS.USER_ID
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_USERS.USER_NAME
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_USERS.PERSON_ID
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_USERS.DATE_FROM
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private Date dateFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_USERS.DATE_TO
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private Date dateTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_USERS.CREATED_BY
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_USERS.CREATION_DATE
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_USERS.LAST_UPDATED_BY
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_USERS.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAM_USERS.LAST_LOGGED_IN
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private Date lastLoggedIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SAM_USERS
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_USERS.USER_ID
     *
     * @return the value of SAM_USERS.USER_ID
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_USERS.USER_ID
     *
     * @param id the value for SAM_USERS.USER_ID
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_USERS.USER_NAME
     *
     * @return the value of SAM_USERS.USER_NAME
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_USERS.USER_NAME
     *
     * @param userName the value for SAM_USERS.USER_NAME
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_USERS.PERSON_ID
     *
     * @return the value of SAM_USERS.PERSON_ID
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_USERS.PERSON_ID
     *
     * @param personId the value for SAM_USERS.PERSON_ID
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_USERS.DATE_FROM
     *
     * @return the value of SAM_USERS.DATE_FROM
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public Date getDateFrom() {
        return dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_USERS.DATE_FROM
     *
     * @param dateFrom the value for SAM_USERS.DATE_FROM
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_USERS.DATE_TO
     *
     * @return the value of SAM_USERS.DATE_TO
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public Date getDateTo() {
        return dateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_USERS.DATE_TO
     *
     * @param dateTo the value for SAM_USERS.DATE_TO
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_USERS.CREATED_BY
     *
     * @return the value of SAM_USERS.CREATED_BY
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_USERS.CREATED_BY
     *
     * @param createdBy the value for SAM_USERS.CREATED_BY
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_USERS.CREATION_DATE
     *
     * @return the value of SAM_USERS.CREATION_DATE
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_USERS.CREATION_DATE
     *
     * @param creationDate the value for SAM_USERS.CREATION_DATE
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_USERS.LAST_UPDATED_BY
     *
     * @return the value of SAM_USERS.LAST_UPDATED_BY
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_USERS.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for SAM_USERS.LAST_UPDATED_BY
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_USERS.LAST_UPDATE_DATE
     *
     * @return the value of SAM_USERS.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_USERS.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for SAM_USERS.LAST_UPDATE_DATE
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAM_USERS.LAST_LOGGED_IN
     *
     * @return the value of SAM_USERS.LAST_LOGGED_IN
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public Date getLastLoggedIn() {
        return lastLoggedIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAM_USERS.LAST_LOGGED_IN
     *
     * @param lastLoggedIn the value for SAM_USERS.LAST_LOGGED_IN
     *
     * @mbggenerated Fri Sep 27 17:34:46 ICT 2013
     */
    public void setLastLoggedIn(Date lastLoggedIn) {
        this.lastLoggedIn = lastLoggedIn;
    }
}