package co.id.fifgroup.systemadmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.systemadmin.domain.AuditDetail;
import co.id.fifgroup.systemadmin.domain.AuditDetailExample;

public interface AuditDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    int countByExample(AuditDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    int deleteByPrimaryKey(byte[] attributeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    int insert(AuditDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    int insertSelective(AuditDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    List<AuditDetail> selectByExampleWithBLOBsWithRowbounds(AuditDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    List<AuditDetail> selectByExampleWithBLOBs(AuditDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    List<AuditDetail> selectByExampleWithRowbounds(AuditDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    List<AuditDetail> selectByExample(AuditDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    AuditDetail selectByPrimaryKey(byte[] attributeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    int updateByExampleSelective(@Param("record") AuditDetail record, @Param("example") AuditDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    int updateByExampleWithBLOBs(@Param("record") AuditDetail record, @Param("example") AuditDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    int updateByExample(@Param("record") AuditDetail record, @Param("example") AuditDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    int updateByPrimaryKeySelective(AuditDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    int updateByPrimaryKeyWithBLOBs(AuditDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_AUDIT_DETAIL
     *
     * @mbggenerated Mon Apr 15 18:20:36 ICT 2013
     */
    int updateByPrimaryKey(AuditDetail record);
}