package co.id.fifgroup.systemadmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.systemadmin.domain.Function;
import co.id.fifgroup.systemadmin.domain.FunctionExample;

public interface FunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    int countByExample(FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    int insert(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    int insertSelective(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    List<Function> selectByExampleWithRowbounds(FunctionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    List<Function> selectByExample(FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    Function selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    int updateByExampleSelective(@Param("record") Function record, @Param("example") FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    int updateByExample(@Param("record") Function record, @Param("example") FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    int updateByPrimaryKeySelective(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_FUNCTIONS
     *
     * @mbggenerated Tue Mar 19 11:08:32 ICT 2013
     */
    int updateByPrimaryKey(Function record);
}