package co.id.fifgroup.systemadmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.systemadmin.domain.ModuleErrorLog;
import co.id.fifgroup.systemadmin.domain.ModuleErrorLogExample;

public interface ModuleErrorLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    int countByExample(ModuleErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    int deleteByPrimaryKey(Long errorLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    int insert(ModuleErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    int insertSelective(ModuleErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    List<ModuleErrorLog> selectByExampleWithRowbounds(ModuleErrorLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    List<ModuleErrorLog> selectByExample(ModuleErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    ModuleErrorLog selectByPrimaryKey(Long errorLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    int updateByExampleSelective(@Param("record") ModuleErrorLog record, @Param("example") ModuleErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    int updateByExample(@Param("record") ModuleErrorLog record, @Param("example") ModuleErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    int updateByPrimaryKeySelective(ModuleErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_MODULE_ERROR_LOGS
     *
     * @mbggenerated Wed Apr 03 11:37:54 ICT 2013
     */
    int updateByPrimaryKey(ModuleErrorLog record);
}