package co.id.fifgroup.systemadmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import co.id.fifgroup.systemadmin.domain.ResponsibilityCompany;
import co.id.fifgroup.systemadmin.domain.ResponsibilityCompanyExample;

public interface ResponsibilityCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_RESPONSIBILITY_COMPANIES
     *
     * @mbggenerated Mon Feb 25 18:51:54 ICT 2013
     */
    int countByExample(ResponsibilityCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_RESPONSIBILITY_COMPANIES
     *
     * @mbggenerated Mon Feb 25 18:51:54 ICT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_RESPONSIBILITY_COMPANIES
     *
     * @mbggenerated Mon Feb 25 18:51:54 ICT 2013
     */
    int insert(ResponsibilityCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_RESPONSIBILITY_COMPANIES
     *
     * @mbggenerated Mon Feb 25 18:51:54 ICT 2013
     */
    int insertSelective(ResponsibilityCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_RESPONSIBILITY_COMPANIES
     *
     * @mbggenerated Mon Feb 25 18:51:54 ICT 2013
     */
    List<ResponsibilityCompany> selectByExample(ResponsibilityCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_RESPONSIBILITY_COMPANIES
     *
     * @mbggenerated Mon Feb 25 18:51:54 ICT 2013
     */
    ResponsibilityCompany selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_RESPONSIBILITY_COMPANIES
     *
     * @mbggenerated Mon Feb 25 18:51:54 ICT 2013
     */
    int updateByExampleSelective(@Param("record") ResponsibilityCompany record, @Param("example") ResponsibilityCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_RESPONSIBILITY_COMPANIES
     *
     * @mbggenerated Mon Feb 25 18:51:54 ICT 2013
     */
    int updateByExample(@Param("record") ResponsibilityCompany record, @Param("example") ResponsibilityCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_RESPONSIBILITY_COMPANIES
     *
     * @mbggenerated Mon Feb 25 18:51:54 ICT 2013
     */
    int updateByPrimaryKeySelective(ResponsibilityCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_RESPONSIBILITY_COMPANIES
     *
     * @mbggenerated Mon Feb 25 18:51:54 ICT 2013
     */
    int updateByPrimaryKey(ResponsibilityCompany record);
}