package co.id.fifgroup.systemadmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.systemadmin.domain.Task;
import co.id.fifgroup.systemadmin.domain.TaskExample;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    int countByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    List<Task> selectByExampleWithRowbounds(TaskExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    Task selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    int updateByExampleSelective(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    int updateByExample(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASKS
     *
     * @mbggenerated Wed Jul 17 14:13:43 ICT 2013
     */
    int updateByPrimaryKey(Task record);
}