package co.id.fifgroup.systemadmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.systemadmin.domain.TaskParameter;
import co.id.fifgroup.systemadmin.domain.TaskParameterExample;

public interface TaskParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    int countByExample(TaskParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    int insert(TaskParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    int insertSelective(TaskParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    List<TaskParameter> selectByExampleWithRowbounds(TaskParameterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    List<TaskParameter> selectByExample(TaskParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    TaskParameter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    int updateByExampleSelective(@Param("record") TaskParameter record, @Param("example") TaskParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    int updateByExample(@Param("record") TaskParameter record, @Param("example") TaskParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    int updateByPrimaryKeySelective(TaskParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_PARAMETERS
     *
     * @mbggenerated Thu Feb 06 13:28:57 ICT 2014
     */
    int updateByPrimaryKey(TaskParameter record);
}