package co.id.fifgroup.systemadmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.systemadmin.domain.TaskRequest;
import co.id.fifgroup.systemadmin.domain.TaskRequestExample;

public interface TaskRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    int countByExample(TaskRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    int insert(TaskRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    int insertSelective(TaskRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    List<TaskRequest> selectByExampleWithRowbounds(TaskRequestExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    List<TaskRequest> selectByExample(TaskRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    TaskRequest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    int updateByExampleSelective(@Param("record") TaskRequest record, @Param("example") TaskRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    int updateByExample(@Param("record") TaskRequest record, @Param("example") TaskRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    int updateByPrimaryKeySelective(TaskRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_REQUESTS
     *
     * @mbggenerated Thu Jun 13 16:05:34 ICT 2013
     */
    int updateByPrimaryKey(TaskRequest record);
}