package co.id.fifgroup.systemadmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.systemadmin.domain.TaskGroupDetail;
import co.id.fifgroup.systemadmin.domain.TaskGroupDetailExample;

public interface TaskGroupDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    int countByExample(TaskGroupDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    int insert(TaskGroupDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    int insertSelective(TaskGroupDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    List<TaskGroupDetail> selectByExampleWithRowbounds(TaskGroupDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    List<TaskGroupDetail> selectByExample(TaskGroupDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    TaskGroupDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    int updateByExampleSelective(@Param("record") TaskGroupDetail record, @Param("example") TaskGroupDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    int updateByExample(@Param("record") TaskGroupDetail record, @Param("example") TaskGroupDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    int updateByPrimaryKeySelective(TaskGroupDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_TASK_GROUP_DTL
     *
     * @mbggenerated Tue Mar 19 21:54:16 ICT 2013
     */
    int updateByPrimaryKey(TaskGroupDetail record);
}