package co.id.fifgroup.systemadmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.systemadmin.domain.UserResponsibility;
import co.id.fifgroup.systemadmin.domain.UserResponsibilityExample;

public interface UserResponsibilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    int countByExample(UserResponsibilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    int insert(UserResponsibility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    int insertSelective(UserResponsibility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    List<UserResponsibility> selectByExampleWithRowbounds(UserResponsibilityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    List<UserResponsibility> selectByExample(UserResponsibilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    UserResponsibility selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    int updateByExampleSelective(@Param("record") UserResponsibility record, @Param("example") UserResponsibilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    int updateByExample(@Param("record") UserResponsibility record, @Param("example") UserResponsibilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    int updateByPrimaryKeySelective(UserResponsibility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAM_USER_RESPONSIBILITIES
     *
     * @mbggenerated Tue Mar 19 23:28:06 ICT 2013
     */
    int updateByPrimaryKey(UserResponsibility record);
}