package co.id.fifgroup.systemadmin.constant;

public enum NotificationTransactionType {
	OCOP_EMPLOYEE_MUTATION,
	OCOP_EMPLOYEE_MUTATION_INDENT,
	OCOP_NOT_ELIGIBILE,
	OCOP_BRANCH_CHANGES,
	OCOP_NEW_OCOP_AVAILABLE,
	OCOP_REMINDER_FOR_CLOSURE,
	OCOP_TERMINATED_EMP_CAR_INDENT,
	OCOP_TERMINATED_EMP_CLOSURE,
	OCOP_CLOSURE_NORMAL,
	OCOP_START_DEDUCTION,
	OCOP_NEW_REQUEST,
	WEQ_NOT_SUBMIT_REQUEST,
	WEQ_EXPIRED_PERIOD,
	// Added by Jatis for CWK
	CWK_HIRE_CWK_DOCUMENT_APPROVED,
	CWK_HIRE_CWK_DOCUMENT_REJECTED,
	CWK_HIRE_CWK_DOCUMENT_REVISE,
	CWK_HIRE_CWK_DOCUMENT_SUBMITED,
	CWK_HIRE_CWK_TO_PROBATION_APPROVED,
	CWK_HIRE_CWK_TO_PROBATION_REJECTED,
	CWK_TERMINATION_CWK_APPROVED,
	CWK_TERMINATION_CWK_REJECTED,
	CWK_TERMINATION_REVERSE_APPROVED,
	CWK_TERMINATION_REVERSE_REJECTED,
	CWK_REQUISITION_UPDATE,
	CWK_DAILY_ASSIGNMENT_CREATED,
	CWK_DAILY_PKWT_HISTORIES_CREATED,
	CWK_AUTOHIRED_DAILY,
	// End Added by Jatis for CWK
	OCOP_CLOSURE_MANUAL,
	OCOP_TERMINATION_INDENT,
	OCOP_TRANSFER_INDENT,
	OCOP_PROMOTION_INDENT,
	WEQ_LATEST_REQUEST, 
	WEQ_LATEST_ORDER, 
	// Added by Jatis for CWK
	CWK_HIRE_CWK_TO_PROBATION_REJECTED_EMAIL_DASHBOARD,
	CWK_HIRE_CWK_TO_PROBATION_APPROVED_EMAIL_DASHBOARD,
	// End Added by Jatis for CWK
	ILE_MODULE_UPLOAD_BEFORE_DUE_DATE,
	ILE_MODULE_UPLOAD_AFTER_DUE_DATE,
	// start added by WLY, training admin notification
	TRA_SPP_AGREEMENT_CONFIRMATION_NOTIFICATION,
	TRA_SPP_AGREEMENT_INFORMATION_NOTIFICATION,
	TRA_IN_CLASS_DEV_SCORE_NOTIFICATION,
	TRA_EEVELUATION_BEFORE_DEV_NOTIFICATION,
	TRA_EEVELUATION_AFTER_DEV_NOTIFICATION,
	TRA_ENROLLMENT_CANCELLED_NOTIFICATION,
	TRA_ENROLLMENT_VALIDATED_NOTIFICATION,
	TRA_SELF_ENROLLMENT_NOTIFICATION, //778
	TRA_PROPOSAL_CREATION_NOTIFICATION, //780
	TRA_IN_CLASS_SCORE_FOR_INSTRUCTOR_IN_NOTIFICATION, //796
	TRA_IN_CLASS_SCORE_FOR_INSTRUCTOR_EX_NOTIFICATION,
	TRA_IN_CLASS_SCORE_FOR_ATTENDANCE_NOTIFICATION,
	TRA_DEV_PROPOSAL_CANCELLED_NOTIFICATION,
	TRA_IN_CLASS_DEV_RESULT_PARTICIPANT_NOTIFICATION, 
	TRA_SPP_DEMOTION_NOTIFICATION, 
	TRA_SPP_TERMINATION_NOTIFICATION,
	TRA_POST_ACTIVITY_RESULT_NOTIFICATION,
	TRA_EVALUATOR_AFTER_POST_ACTIVITY,
	TRA_NEW_JOB_NOTIFICATION
	// end added by WLY, training admin notification
	;
}
