package co.id.fifgroup.workstructure.domain;

import java.io.Serializable;
import java.util.Date;

public class LocationVersion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.VERSION_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Long versionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.LOCATION_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.VERSION_NUMBER
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Integer versionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.DATE_FROM
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Date dateFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.DATE_TO
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Date dateTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.DESCRIPTION
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.COUNTRY_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.PROVINCE_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.CITY_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.ZONE_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private String zoneCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.WORKING_SCHEDULE_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Long workingScheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.CREATED_BY
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.CREATION_DATE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_LOCATION_VERSIONS.BRANCH_OWNER_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private Long branchOwnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WOS_LOCATION_VERSIONS
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.VERSION_ID
     *
     * @return the value of WOS_LOCATION_VERSIONS.VERSION_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Long getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.VERSION_ID
     *
     * @param versionId the value for WOS_LOCATION_VERSIONS.VERSION_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.LOCATION_ID
     *
     * @return the value of WOS_LOCATION_VERSIONS.LOCATION_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.LOCATION_ID
     *
     * @param id the value for WOS_LOCATION_VERSIONS.LOCATION_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.VERSION_NUMBER
     *
     * @return the value of WOS_LOCATION_VERSIONS.VERSION_NUMBER
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Integer getVersionNumber() {
        return versionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.VERSION_NUMBER
     *
     * @param versionNumber the value for WOS_LOCATION_VERSIONS.VERSION_NUMBER
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setVersionNumber(Integer versionNumber) {
        this.versionNumber = versionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.DATE_FROM
     *
     * @return the value of WOS_LOCATION_VERSIONS.DATE_FROM
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Date getDateFrom() {
        return dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.DATE_FROM
     *
     * @param dateFrom the value for WOS_LOCATION_VERSIONS.DATE_FROM
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.DATE_TO
     *
     * @return the value of WOS_LOCATION_VERSIONS.DATE_TO
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Date getDateTo() {
        return dateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.DATE_TO
     *
     * @param dateTo the value for WOS_LOCATION_VERSIONS.DATE_TO
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.DESCRIPTION
     *
     * @return the value of WOS_LOCATION_VERSIONS.DESCRIPTION
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.DESCRIPTION
     *
     * @param description the value for WOS_LOCATION_VERSIONS.DESCRIPTION
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.COUNTRY_CODE
     *
     * @return the value of WOS_LOCATION_VERSIONS.COUNTRY_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.COUNTRY_CODE
     *
     * @param countryCode the value for WOS_LOCATION_VERSIONS.COUNTRY_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.PROVINCE_CODE
     *
     * @return the value of WOS_LOCATION_VERSIONS.PROVINCE_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.PROVINCE_CODE
     *
     * @param provinceCode the value for WOS_LOCATION_VERSIONS.PROVINCE_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.CITY_CODE
     *
     * @return the value of WOS_LOCATION_VERSIONS.CITY_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.CITY_CODE
     *
     * @param cityCode the value for WOS_LOCATION_VERSIONS.CITY_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.ZONE_CODE
     *
     * @return the value of WOS_LOCATION_VERSIONS.ZONE_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public String getZoneCode() {
        return zoneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.ZONE_CODE
     *
     * @param zoneCode the value for WOS_LOCATION_VERSIONS.ZONE_CODE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setZoneCode(String zoneCode) {
        this.zoneCode = zoneCode == null ? null : zoneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.WORKING_SCHEDULE_ID
     *
     * @return the value of WOS_LOCATION_VERSIONS.WORKING_SCHEDULE_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Long getWorkingScheduleId() {
        return workingScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.WORKING_SCHEDULE_ID
     *
     * @param workingScheduleId the value for WOS_LOCATION_VERSIONS.WORKING_SCHEDULE_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setWorkingScheduleId(Long workingScheduleId) {
        this.workingScheduleId = workingScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.CREATED_BY
     *
     * @return the value of WOS_LOCATION_VERSIONS.CREATED_BY
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.CREATED_BY
     *
     * @param createdBy the value for WOS_LOCATION_VERSIONS.CREATED_BY
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.CREATION_DATE
     *
     * @return the value of WOS_LOCATION_VERSIONS.CREATION_DATE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.CREATION_DATE
     *
     * @param creationDate the value for WOS_LOCATION_VERSIONS.CREATION_DATE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.LAST_UPDATED_BY
     *
     * @return the value of WOS_LOCATION_VERSIONS.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for WOS_LOCATION_VERSIONS.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.LAST_UPDATE_DATE
     *
     * @return the value of WOS_LOCATION_VERSIONS.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for WOS_LOCATION_VERSIONS.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_LOCATION_VERSIONS.BRANCH_OWNER_ID
     *
     * @return the value of WOS_LOCATION_VERSIONS.BRANCH_OWNER_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public Long getBranchOwnerId() {
        return branchOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_LOCATION_VERSIONS.BRANCH_OWNER_ID
     *
     * @param branchOwnerId the value for WOS_LOCATION_VERSIONS.BRANCH_OWNER_ID
     *
     * @mbggenerated Wed Dec 18 21:54:05 ICT 2013
     */
    public void setBranchOwnerId(Long branchOwnerId) {
        this.branchOwnerId = branchOwnerId;
    }
}