package co.id.fifgroup.workstructure.domain;

import java.io.Serializable;
import java.util.Date;

public class OrgHierarchyElement implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_ORG_HIER_ELEMENTS.ORG_HIER_ELEMENT_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    private Long orgHierElementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_ORG_HIER_ELEMENTS.COMPANY_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_ORG_HIER_ELEMENTS.VERSION_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    private Long versionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_ORG_HIER_ELEMENTS.PARENT_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_ORG_HIER_ELEMENTS.ORGANIZATION_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    private Long organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_ORG_HIER_ELEMENTS.CREATED_BY
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_ORG_HIER_ELEMENTS.CREATION_DATE
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_ORG_HIER_ELEMENTS.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WOS_ORG_HIER_ELEMENTS.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WOS_ORG_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_ORG_HIER_ELEMENTS.ORG_HIER_ELEMENT_ID
     *
     * @return the value of WOS_ORG_HIER_ELEMENTS.ORG_HIER_ELEMENT_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public Long getOrgHierElementId() {
        return orgHierElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_ORG_HIER_ELEMENTS.ORG_HIER_ELEMENT_ID
     *
     * @param orgHierElementId the value for WOS_ORG_HIER_ELEMENTS.ORG_HIER_ELEMENT_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public void setOrgHierElementId(Long orgHierElementId) {
        this.orgHierElementId = orgHierElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_ORG_HIER_ELEMENTS.COMPANY_ID
     *
     * @return the value of WOS_ORG_HIER_ELEMENTS.COMPANY_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_ORG_HIER_ELEMENTS.COMPANY_ID
     *
     * @param companyId the value for WOS_ORG_HIER_ELEMENTS.COMPANY_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_ORG_HIER_ELEMENTS.VERSION_ID
     *
     * @return the value of WOS_ORG_HIER_ELEMENTS.VERSION_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public Long getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_ORG_HIER_ELEMENTS.VERSION_ID
     *
     * @param versionId the value for WOS_ORG_HIER_ELEMENTS.VERSION_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_ORG_HIER_ELEMENTS.PARENT_ID
     *
     * @return the value of WOS_ORG_HIER_ELEMENTS.PARENT_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_ORG_HIER_ELEMENTS.PARENT_ID
     *
     * @param parentId the value for WOS_ORG_HIER_ELEMENTS.PARENT_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_ORG_HIER_ELEMENTS.ORGANIZATION_ID
     *
     * @return the value of WOS_ORG_HIER_ELEMENTS.ORGANIZATION_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_ORG_HIER_ELEMENTS.ORGANIZATION_ID
     *
     * @param organizationId the value for WOS_ORG_HIER_ELEMENTS.ORGANIZATION_ID
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_ORG_HIER_ELEMENTS.CREATED_BY
     *
     * @return the value of WOS_ORG_HIER_ELEMENTS.CREATED_BY
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_ORG_HIER_ELEMENTS.CREATED_BY
     *
     * @param createdBy the value for WOS_ORG_HIER_ELEMENTS.CREATED_BY
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_ORG_HIER_ELEMENTS.CREATION_DATE
     *
     * @return the value of WOS_ORG_HIER_ELEMENTS.CREATION_DATE
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_ORG_HIER_ELEMENTS.CREATION_DATE
     *
     * @param creationDate the value for WOS_ORG_HIER_ELEMENTS.CREATION_DATE
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_ORG_HIER_ELEMENTS.LAST_UPDATED_BY
     *
     * @return the value of WOS_ORG_HIER_ELEMENTS.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_ORG_HIER_ELEMENTS.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for WOS_ORG_HIER_ELEMENTS.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WOS_ORG_HIER_ELEMENTS.LAST_UPDATE_DATE
     *
     * @return the value of WOS_ORG_HIER_ELEMENTS.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WOS_ORG_HIER_ELEMENTS.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for WOS_ORG_HIER_ELEMENTS.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}