package co.id.fifgroup.eligibility.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import co.id.fifgroup.eligibility.domain.DecisionTableStage;
import co.id.fifgroup.eligibility.domain.DecisionTableStageExample;

public interface DecisionTableStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_UPLOAD_STG
     *
     * @mbggenerated Sat Jul 20 04:44:35 ICT 2013
     */
    int countByExample(@Param("modulePrefix") String modulePrefix, @Param("example")  DecisionTableStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_UPLOAD_STG
     *
     * @mbggenerated Sat Jul 20 04:44:35 ICT 2013
     */
    int deleteByExample(@Param("modulePrefix") String modulePrefix, @Param("example")  DecisionTableStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_UPLOAD_STG
     *
     * @mbggenerated Sat Jul 20 04:44:35 ICT 2013
     */
    int insert(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTableStage record);
    
    /**
	 * [16022316000474] HCMS ph 2- CAM - performance upload career path
	 * Jika ingin insert data dalam jumlah banyak, lebih bagus menggunakan metode bulk
	 * ex: insert data per 500 records
	 * By Jatis (HS) 24/03/2016
	 */
    int insertBulk(@Param("modulePrefix") String modulePrefix, @Param("record") List<DecisionTableStage> record);
    //END [16022316000474]
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_UPLOAD_STG
     *
     * @mbggenerated Sat Jul 20 04:44:35 ICT 2013
     */
    int insertSelective(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTableStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_UPLOAD_STG
     *
     * @mbggenerated Sat Jul 20 04:44:35 ICT 2013
     */
    List<DecisionTableStage> selectByExample(@Param("modulePrefix") String modulePrefix, @Param("example")  DecisionTableStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_UPLOAD_STG
     *
     * @mbggenerated Sat Jul 20 04:44:35 ICT 2013
     */
    int updateByExampleSelective(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTableStage record, @Param("example") DecisionTableStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_UPLOAD_STG
     *
     * @mbggenerated Sat Jul 20 04:44:35 ICT 2013
     */
    int updateByExample(@Param("modulePrefix")String modulePrefix, @Param("record") DecisionTableStage record, @Param("example") DecisionTableStageExample example);
}