package co.id.fifgroup.eligibility.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.id.fifgroup.eligibility.domain.DecisionTable;
import co.id.fifgroup.eligibility.domain.DecisionTableExample;

public interface DecisionTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int countByExample(@Param("modulePrefix") String modulePrefix, @Param("example") DecisionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int deleteByExample(@Param("modulePrefix") String modulePrefix, @Param("example") DecisionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int deleteByPrimaryKey(@Param("modulePrefix") String modulePrefix, @Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int insert(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int insertSelective(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    List<DecisionTable> selectByExampleWithBLOBs(@Param("modulePrefix") String modulePrefix, @Param("example") DecisionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    List<DecisionTable> selectByExample(@Param("modulePrefix") String modulePrefix, @Param("example") DecisionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    DecisionTable selectByPrimaryKey(@Param("modulePrefix") String modulePrefix, @Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int updateByExampleSelective(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTable record, @Param("example") DecisionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int updateByExampleWithBLOBs(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTable record, @Param("example") DecisionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int updateByExample(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTable record, @Param("example") DecisionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int updateByPrimaryKeySelective(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int updateByPrimaryKeyWithBLOBs(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELR_DEC_TABLES
     *
     * @mbggenerated Mon Apr 22 05:45:20 WIT 2013
     */
    int updateByPrimaryKey(@Param("modulePrefix") String modulePrefix, @Param("record") DecisionTable record);
}