package co.id.fifgroup.basicsetup.domain;

import java.io.Serializable;
import java.util.Date;

public class OtherInfoDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.OTHER_INFO_DTL_ID
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Long otherInfoDtlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.OTHER_INFO_HDR_ID
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Long otherInfoHdrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.DETAIL_CODE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private String detailCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.PROMPT_NAME
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private String promptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.DATA_TYPE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.IS_MANDATORY
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Boolean isMandatory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.LOOKUP_ID
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Long lookupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.IS_ENABLED
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Boolean isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.IS_DISPLAYED
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Boolean isDisplayed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.MAX_LENGTH
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Integer maxLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.COMPANY_SCOPE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Long companyScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.CREATED_BY
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.CREATION_DATE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_OTHER_INFO_DTL.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BSE_OTHER_INFO_DTL
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.OTHER_INFO_DTL_ID
     *
     * @return the value of BSE_OTHER_INFO_DTL.OTHER_INFO_DTL_ID
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Long getOtherInfoDtlId() {
        return otherInfoDtlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.OTHER_INFO_DTL_ID
     *
     * @param otherInfoDtlId the value for BSE_OTHER_INFO_DTL.OTHER_INFO_DTL_ID
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setOtherInfoDtlId(Long otherInfoDtlId) {
        this.otherInfoDtlId = otherInfoDtlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.OTHER_INFO_HDR_ID
     *
     * @return the value of BSE_OTHER_INFO_DTL.OTHER_INFO_HDR_ID
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Long getOtherInfoHdrId() {
        return otherInfoHdrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.OTHER_INFO_HDR_ID
     *
     * @param otherInfoHdrId the value for BSE_OTHER_INFO_DTL.OTHER_INFO_HDR_ID
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setOtherInfoHdrId(Long otherInfoHdrId) {
        this.otherInfoHdrId = otherInfoHdrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.DETAIL_CODE
     *
     * @return the value of BSE_OTHER_INFO_DTL.DETAIL_CODE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public String getDetailCode() {
        return detailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.DETAIL_CODE
     *
     * @param detailCode the value for BSE_OTHER_INFO_DTL.DETAIL_CODE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setDetailCode(String detailCode) {
        this.detailCode = detailCode == null ? null : detailCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.PROMPT_NAME
     *
     * @return the value of BSE_OTHER_INFO_DTL.PROMPT_NAME
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public String getPromptName() {
        return promptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.PROMPT_NAME
     *
     * @param promptName the value for BSE_OTHER_INFO_DTL.PROMPT_NAME
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setPromptName(String promptName) {
        this.promptName = promptName == null ? null : promptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.DATA_TYPE
     *
     * @return the value of BSE_OTHER_INFO_DTL.DATA_TYPE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.DATA_TYPE
     *
     * @param dataType the value for BSE_OTHER_INFO_DTL.DATA_TYPE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.IS_MANDATORY
     *
     * @return the value of BSE_OTHER_INFO_DTL.IS_MANDATORY
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Boolean getIsMandatory() {
        return isMandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.IS_MANDATORY
     *
     * @param isMandatory the value for BSE_OTHER_INFO_DTL.IS_MANDATORY
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setIsMandatory(Boolean isMandatory) {
        this.isMandatory = isMandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.LOOKUP_ID
     *
     * @return the value of BSE_OTHER_INFO_DTL.LOOKUP_ID
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Long getLookupId() {
        return lookupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.LOOKUP_ID
     *
     * @param lookupId the value for BSE_OTHER_INFO_DTL.LOOKUP_ID
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setLookupId(Long lookupId) {
        this.lookupId = lookupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.IS_ENABLED
     *
     * @return the value of BSE_OTHER_INFO_DTL.IS_ENABLED
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.IS_ENABLED
     *
     * @param isEnabled the value for BSE_OTHER_INFO_DTL.IS_ENABLED
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.IS_DISPLAYED
     *
     * @return the value of BSE_OTHER_INFO_DTL.IS_DISPLAYED
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Boolean getIsDisplayed() {
        return isDisplayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.IS_DISPLAYED
     *
     * @param isDisplayed the value for BSE_OTHER_INFO_DTL.IS_DISPLAYED
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setIsDisplayed(Boolean isDisplayed) {
        this.isDisplayed = isDisplayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.MAX_LENGTH
     *
     * @return the value of BSE_OTHER_INFO_DTL.MAX_LENGTH
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Integer getMaxLength() {
        return maxLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.MAX_LENGTH
     *
     * @param maxLength the value for BSE_OTHER_INFO_DTL.MAX_LENGTH
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setMaxLength(Integer maxLength) {
        this.maxLength = maxLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.COMPANY_SCOPE
     *
     * @return the value of BSE_OTHER_INFO_DTL.COMPANY_SCOPE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Long getCompanyScope() {
        return companyScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.COMPANY_SCOPE
     *
     * @param companyScope the value for BSE_OTHER_INFO_DTL.COMPANY_SCOPE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setCompanyScope(Long companyScope) {
        this.companyScope = companyScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.CREATED_BY
     *
     * @return the value of BSE_OTHER_INFO_DTL.CREATED_BY
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.CREATED_BY
     *
     * @param createdBy the value for BSE_OTHER_INFO_DTL.CREATED_BY
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.CREATION_DATE
     *
     * @return the value of BSE_OTHER_INFO_DTL.CREATION_DATE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.CREATION_DATE
     *
     * @param creationDate the value for BSE_OTHER_INFO_DTL.CREATION_DATE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.LAST_UPDATED_BY
     *
     * @return the value of BSE_OTHER_INFO_DTL.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for BSE_OTHER_INFO_DTL.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_OTHER_INFO_DTL.LAST_UPDATE_DATE
     *
     * @return the value of BSE_OTHER_INFO_DTL.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_OTHER_INFO_DTL.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for BSE_OTHER_INFO_DTL.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Mar 21 20:08:45 ICT 2013
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}