package co.id.fifgroup.basicsetup.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PrinterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public PrinterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrinterIdIsNull() {
            addCriterion("PRINTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andPrinterIdIsNotNull() {
            addCriterion("PRINTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPrinterIdEqualTo(Long value) {
            addCriterion("PRINTER_ID =", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdNotEqualTo(Long value) {
            addCriterion("PRINTER_ID <>", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdGreaterThan(Long value) {
            addCriterion("PRINTER_ID >", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PRINTER_ID >=", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdLessThan(Long value) {
            addCriterion("PRINTER_ID <", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdLessThanOrEqualTo(Long value) {
            addCriterion("PRINTER_ID <=", value, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdIn(List<Long> values) {
            addCriterion("PRINTER_ID in", values, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdNotIn(List<Long> values) {
            addCriterion("PRINTER_ID not in", values, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdBetween(Long value1, Long value2) {
            addCriterion("PRINTER_ID between", value1, value2, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterIdNotBetween(Long value1, Long value2) {
            addCriterion("PRINTER_ID not between", value1, value2, "printerId");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeIsNull() {
            addCriterion("PRINTER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeIsNotNull() {
            addCriterion("PRINTER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeEqualTo(String value) {
            addCriterion("PRINTER_CODE =", value, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeNotEqualTo(String value) {
            addCriterion("PRINTER_CODE <>", value, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeGreaterThan(String value) {
            addCriterion("PRINTER_CODE >", value, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PRINTER_CODE >=", value, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeLessThan(String value) {
            addCriterion("PRINTER_CODE <", value, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeLessThanOrEqualTo(String value) {
            addCriterion("PRINTER_CODE <=", value, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeLike(String value) {
            addCriterion("PRINTER_CODE like", value, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeNotLike(String value) {
            addCriterion("PRINTER_CODE not like", value, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeIn(List<String> values) {
            addCriterion("PRINTER_CODE in", values, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeNotIn(List<String> values) {
            addCriterion("PRINTER_CODE not in", values, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeBetween(String value1, String value2) {
            addCriterion("PRINTER_CODE between", value1, value2, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeNotBetween(String value1, String value2) {
            addCriterion("PRINTER_CODE not between", value1, value2, "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterNameIsNull() {
            addCriterion("PRINTER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPrinterNameIsNotNull() {
            addCriterion("PRINTER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPrinterNameEqualTo(String value) {
            addCriterion("PRINTER_NAME =", value, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameNotEqualTo(String value) {
            addCriterion("PRINTER_NAME <>", value, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameGreaterThan(String value) {
            addCriterion("PRINTER_NAME >", value, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameGreaterThanOrEqualTo(String value) {
            addCriterion("PRINTER_NAME >=", value, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameLessThan(String value) {
            addCriterion("PRINTER_NAME <", value, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameLessThanOrEqualTo(String value) {
            addCriterion("PRINTER_NAME <=", value, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameLike(String value) {
            addCriterion("PRINTER_NAME like", value, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameNotLike(String value) {
            addCriterion("PRINTER_NAME not like", value, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameIn(List<String> values) {
            addCriterion("PRINTER_NAME in", values, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameNotIn(List<String> values) {
            addCriterion("PRINTER_NAME not in", values, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameBetween(String value1, String value2) {
            addCriterion("PRINTER_NAME between", value1, value2, "printerName");
            return (Criteria) this;
        }

        public Criteria andPrinterNameNotBetween(String value1, String value2) {
            addCriterion("PRINTER_NAME not between", value1, value2, "printerName");
            return (Criteria) this;
        }

        public Criteria andArgumentIsNull() {
            addCriterion("ARGUMENT is null");
            return (Criteria) this;
        }

        public Criteria andArgumentIsNotNull() {
            addCriterion("ARGUMENT is not null");
            return (Criteria) this;
        }

        public Criteria andArgumentEqualTo(String value) {
            addCriterion("ARGUMENT =", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentNotEqualTo(String value) {
            addCriterion("ARGUMENT <>", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentGreaterThan(String value) {
            addCriterion("ARGUMENT >", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentGreaterThanOrEqualTo(String value) {
            addCriterion("ARGUMENT >=", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentLessThan(String value) {
            addCriterion("ARGUMENT <", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentLessThanOrEqualTo(String value) {
            addCriterion("ARGUMENT <=", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentLike(String value) {
            addCriterion("ARGUMENT like", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentNotLike(String value) {
            addCriterion("ARGUMENT not like", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentIn(List<String> values) {
            addCriterion("ARGUMENT in", values, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentNotIn(List<String> values) {
            addCriterion("ARGUMENT not in", values, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentBetween(String value1, String value2) {
            addCriterion("ARGUMENT between", value1, value2, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentNotBetween(String value1, String value2) {
            addCriterion("ARGUMENT not between", value1, value2, "argument");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Long value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Long value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Long value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Long value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Long value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Long> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Long> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Long value1, Long value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Long value1, Long value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNull() {
            addCriterion("CREATION_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNotNull() {
            addCriterion("CREATION_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDateEqualTo(Date value) {
            addCriterion("CREATION_DATE =", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotEqualTo(Date value) {
            addCriterion("CREATION_DATE <>", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThan(Date value) {
            addCriterion("CREATION_DATE >", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATION_DATE >=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThan(Date value) {
            addCriterion("CREATION_DATE <", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATION_DATE <=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateIn(List<Date> values) {
            addCriterion("CREATION_DATE in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotIn(List<Date> values) {
            addCriterion("CREATION_DATE not in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateBetween(Date value1, Date value2) {
            addCriterion("CREATION_DATE between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATION_DATE not between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNull() {
            addCriterion("LAST_UPDATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNotNull() {
            addCriterion("LAST_UPDATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY =", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY <>", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThan(Long value) {
            addCriterion("LAST_UPDATED_BY >", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY >=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThan(Long value) {
            addCriterion("LAST_UPDATED_BY <", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThanOrEqualTo(Long value) {
            addCriterion("LAST_UPDATED_BY <=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIn(List<Long> values) {
            addCriterion("LAST_UPDATED_BY in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotIn(List<Long> values) {
            addCriterion("LAST_UPDATED_BY not in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByBetween(Long value1, Long value2) {
            addCriterion("LAST_UPDATED_BY between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotBetween(Long value1, Long value2) {
            addCriterion("LAST_UPDATED_BY not between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andPrinterCodeLikeInsensitive(String value) {
            addCriterion("upper(PRINTER_CODE) like", value.toUpperCase(), "printerCode");
            return (Criteria) this;
        }

        public Criteria andPrinterNameLikeInsensitive(String value) {
            addCriterion("upper(PRINTER_NAME) like", value.toUpperCase(), "printerName");
            return (Criteria) this;
        }

        public Criteria andArgumentLikeInsensitive(String value) {
            addCriterion("upper(ARGUMENT) like", value.toUpperCase(), "argument");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("upper(DESCRIPTION) like", value.toUpperCase(), "description");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 20 11:18:05 ICT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}