package co.id.fifgroup.basicsetup.domain;

import java.io.Serializable;
import java.util.Date;

public class SequenceGenerator implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.SEQUENCE_GENERATOR_ID
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Long sequenceGeneratorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.GROUP_ID
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.COMPANY_SCOPE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Long companyScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.TRX_CODE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private String trxCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.LENGTH
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Integer length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.IS_PADDING
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Boolean isPadding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.PADDING_CHAR
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private String paddingChar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.PREFIX
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private String prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.SEQUENCE_START_FROM
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Integer sequenceStartFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.SEQ_INCREMENT
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Integer seqIncrement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.IS_RESET_PER_YEAR
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Boolean isResetPerYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.CREATED_BY
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.CREATION_DATE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Long lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSE_SEQUENCE_GENERATORS.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BSE_SEQUENCE_GENERATORS
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.SEQUENCE_GENERATOR_ID
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.SEQUENCE_GENERATOR_ID
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Long getSequenceGeneratorId() {
        return sequenceGeneratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.SEQUENCE_GENERATOR_ID
     *
     * @param sequenceGeneratorId the value for BSE_SEQUENCE_GENERATORS.SEQUENCE_GENERATOR_ID
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setSequenceGeneratorId(Long sequenceGeneratorId) {
        this.sequenceGeneratorId = sequenceGeneratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.GROUP_ID
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.GROUP_ID
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.GROUP_ID
     *
     * @param groupId the value for BSE_SEQUENCE_GENERATORS.GROUP_ID
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.COMPANY_SCOPE
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.COMPANY_SCOPE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Long getCompanyScope() {
        return companyScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.COMPANY_SCOPE
     *
     * @param companyScope the value for BSE_SEQUENCE_GENERATORS.COMPANY_SCOPE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setCompanyScope(Long companyScope) {
        this.companyScope = companyScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.TRX_CODE
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.TRX_CODE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public String getTrxCode() {
        return trxCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.TRX_CODE
     *
     * @param trxCode the value for BSE_SEQUENCE_GENERATORS.TRX_CODE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setTrxCode(String trxCode) {
        this.trxCode = trxCode == null ? null : trxCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.LENGTH
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.LENGTH
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.LENGTH
     *
     * @param length the value for BSE_SEQUENCE_GENERATORS.LENGTH
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.IS_PADDING
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.IS_PADDING
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Boolean getIsPadding() {
        return isPadding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.IS_PADDING
     *
     * @param isPadding the value for BSE_SEQUENCE_GENERATORS.IS_PADDING
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setIsPadding(Boolean isPadding) {
        this.isPadding = isPadding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.PADDING_CHAR
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.PADDING_CHAR
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public String getPaddingChar() {
        return paddingChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.PADDING_CHAR
     *
     * @param paddingChar the value for BSE_SEQUENCE_GENERATORS.PADDING_CHAR
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setPaddingChar(String paddingChar) {
        this.paddingChar = paddingChar == null ? null : paddingChar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.PREFIX
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.PREFIX
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.PREFIX
     *
     * @param prefix the value for BSE_SEQUENCE_GENERATORS.PREFIX
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix == null ? null : prefix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.SEQUENCE_START_FROM
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.SEQUENCE_START_FROM
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Integer getSequenceStartFrom() {
        return sequenceStartFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.SEQUENCE_START_FROM
     *
     * @param sequenceStartFrom the value for BSE_SEQUENCE_GENERATORS.SEQUENCE_START_FROM
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setSequenceStartFrom(Integer sequenceStartFrom) {
        this.sequenceStartFrom = sequenceStartFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.SEQ_INCREMENT
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.SEQ_INCREMENT
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Integer getSeqIncrement() {
        return seqIncrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.SEQ_INCREMENT
     *
     * @param seqIncrement the value for BSE_SEQUENCE_GENERATORS.SEQ_INCREMENT
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setSeqIncrement(Integer seqIncrement) {
        this.seqIncrement = seqIncrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.IS_RESET_PER_YEAR
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.IS_RESET_PER_YEAR
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Boolean getIsResetPerYear() {
        return isResetPerYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.IS_RESET_PER_YEAR
     *
     * @param isResetPerYear the value for BSE_SEQUENCE_GENERATORS.IS_RESET_PER_YEAR
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setIsResetPerYear(Boolean isResetPerYear) {
        this.isResetPerYear = isResetPerYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.CREATED_BY
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.CREATED_BY
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.CREATED_BY
     *
     * @param createdBy the value for BSE_SEQUENCE_GENERATORS.CREATED_BY
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.CREATION_DATE
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.CREATION_DATE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.CREATION_DATE
     *
     * @param creationDate the value for BSE_SEQUENCE_GENERATORS.CREATION_DATE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.LAST_UPDATED_BY
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for BSE_SEQUENCE_GENERATORS.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSE_SEQUENCE_GENERATORS.LAST_UPDATE_DATE
     *
     * @return the value of BSE_SEQUENCE_GENERATORS.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSE_SEQUENCE_GENERATORS.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for BSE_SEQUENCE_GENERATORS.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Apr 03 11:15:51 ICT 2013
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}