package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.BranchSize;
import co.id.fifgroup.workstructure.domain.BranchSizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BranchSizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    int countByExample(BranchSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    int deleteByExample(BranchSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    int insert(BranchSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    int insertSelective(BranchSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    List<BranchSize> selectByExampleWithRowbounds(BranchSizeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    List<BranchSize> selectByExample(BranchSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    BranchSize selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    int updateByExampleSelective(@Param("record") BranchSize record, @Param("example") BranchSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    int updateByExample(@Param("record") BranchSize record, @Param("example") BranchSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    int updateByPrimaryKeySelective(BranchSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_BRANCH_SIZES
     *
     * @mbggenerated Tue Apr 16 12:09:35 ICT 2013
     */
    int updateByPrimaryKey(BranchSize record);
}