package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.GradeUploadStage;
import co.id.fifgroup.workstructure.domain.GradeUploadStageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GradeUploadStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_STG
     *
     * @mbggenerated Wed Jul 03 15:54:56 ICT 2013
     */
    int countByExample(GradeUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_STG
     *
     * @mbggenerated Wed Jul 03 15:54:56 ICT 2013
     */
    int deleteByExample(GradeUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_STG
     *
     * @mbggenerated Wed Jul 03 15:54:56 ICT 2013
     */
    int insert(GradeUploadStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_STG
     *
     * @mbggenerated Wed Jul 03 15:54:56 ICT 2013
     */
    int insertSelective(GradeUploadStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_STG
     *
     * @mbggenerated Wed Jul 03 15:54:56 ICT 2013
     */
    List<GradeUploadStage> selectByExampleWithRowbounds(GradeUploadStageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_STG
     *
     * @mbggenerated Wed Jul 03 15:54:56 ICT 2013
     */
    List<GradeUploadStage> selectByExample(GradeUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_STG
     *
     * @mbggenerated Wed Jul 03 15:54:56 ICT 2013
     */
    int updateByExampleSelective(@Param("record") GradeUploadStage record, @Param("example") GradeUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_STG
     *
     * @mbggenerated Wed Jul 03 15:54:56 ICT 2013
     */
    int updateByExample(@Param("record") GradeUploadStage record, @Param("example") GradeUploadStageExample example);
}