package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.GradeSetElement;
import co.id.fifgroup.workstructure.domain.GradeSetElementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GradeSetElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int countByExample(GradeSetElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int deleteByExample(GradeSetElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int deleteByPrimaryKey(Long elementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int insert(GradeSetElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int insertSelective(GradeSetElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    List<GradeSetElement> selectByExampleWithRowbounds(GradeSetElementExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    List<GradeSetElement> selectByExample(GradeSetElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    GradeSetElement selectByPrimaryKey(Long elementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByExampleSelective(@Param("record") GradeSetElement record, @Param("example") GradeSetElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByExample(@Param("record") GradeSetElement record, @Param("example") GradeSetElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByPrimaryKeySelective(GradeSetElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_GRADE_SET_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByPrimaryKey(GradeSetElement record);
}