package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.Job;
import co.id.fifgroup.workstructure.domain.JobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface JobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int countByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    List<Job> selectByExampleWithBLOBsWithRowbounds(JobExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    List<Job> selectByExampleWithBLOBs(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    List<Job> selectByExampleWithRowbounds(JobExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    List<Job> selectByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    Job selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int updateByExampleSelective(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int updateByExample(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int updateByPrimaryKeyWithBLOBs(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOBS
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int updateByPrimaryKey(Job record);
}