package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.JobUploadStage;
import co.id.fifgroup.workstructure.domain.JobUploadStageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface JobUploadStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_STG
     *
     * @mbggenerated Wed Jul 03 15:34:16 ICT 2013
     */
    int countByExample(JobUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_STG
     *
     * @mbggenerated Wed Jul 03 15:34:16 ICT 2013
     */
    int deleteByExample(JobUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_STG
     *
     * @mbggenerated Wed Jul 03 15:34:16 ICT 2013
     */
    int insert(JobUploadStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_STG
     *
     * @mbggenerated Wed Jul 03 15:34:16 ICT 2013
     */
    int insertSelective(JobUploadStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_STG
     *
     * @mbggenerated Wed Jul 03 15:34:16 ICT 2013
     */
    List<JobUploadStage> selectByExampleWithRowbounds(JobUploadStageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_STG
     *
     * @mbggenerated Wed Jul 03 15:34:16 ICT 2013
     */
    List<JobUploadStage> selectByExample(JobUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_STG
     *
     * @mbggenerated Wed Jul 03 15:34:16 ICT 2013
     */
    int updateByExampleSelective(@Param("record") JobUploadStage record, @Param("example") JobUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_STG
     *
     * @mbggenerated Wed Jul 03 15:34:16 ICT 2013
     */
    int updateByExample(@Param("record") JobUploadStage record, @Param("example") JobUploadStageExample example);
}