package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.JobValidGrade;
import co.id.fifgroup.workstructure.domain.JobValidGradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface JobValidGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int countByExample(JobValidGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int deleteByExample(JobValidGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int deleteByPrimaryKey(@Param("versionId") Long versionId, @Param("gradeId") Long gradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int insert(JobValidGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int insertSelective(JobValidGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    List<JobValidGrade> selectByExampleWithRowbounds(JobValidGradeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    List<JobValidGrade> selectByExample(JobValidGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    JobValidGrade selectByPrimaryKey(@Param("versionId") Long versionId, @Param("gradeId") Long gradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int updateByExampleSelective(@Param("record") JobValidGrade record, @Param("example") JobValidGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int updateByExample(@Param("record") JobValidGrade record, @Param("example") JobValidGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int updateByPrimaryKeySelective(JobValidGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_JOB_VALID_GRADES
     *
     * @mbggenerated Wed Jan 22 12:12:57 ICT 2014
     */
    int updateByPrimaryKey(JobValidGrade record);
}