package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.Location;
import co.id.fifgroup.workstructure.domain.LocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int countByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int insertSelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    List<Location> selectByExampleWithRowbounds(LocationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    List<Location> selectByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    Location selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByExampleSelective(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByExample(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByPrimaryKeySelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATIONS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByPrimaryKey(Location record);
}