package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.LocationUploadStage;
import co.id.fifgroup.workstructure.domain.LocationUploadStageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LocationUploadStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATION_STG
     *
     * @mbggenerated Thu Jan 30 14:59:01 ICT 2014
     */
    int countByExample(LocationUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATION_STG
     *
     * @mbggenerated Thu Jan 30 14:59:01 ICT 2014
     */
    int deleteByExample(LocationUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATION_STG
     *
     * @mbggenerated Thu Jan 30 14:59:01 ICT 2014
     */
    int insert(LocationUploadStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATION_STG
     *
     * @mbggenerated Thu Jan 30 14:59:01 ICT 2014
     */
    int insertSelective(LocationUploadStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATION_STG
     *
     * @mbggenerated Thu Jan 30 14:59:01 ICT 2014
     */
    List<LocationUploadStage> selectByExampleWithRowbounds(LocationUploadStageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATION_STG
     *
     * @mbggenerated Thu Jan 30 14:59:01 ICT 2014
     */
    List<LocationUploadStage> selectByExample(LocationUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATION_STG
     *
     * @mbggenerated Thu Jan 30 14:59:01 ICT 2014
     */
    int updateByExampleSelective(@Param("record") LocationUploadStage record, @Param("example") LocationUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_LOCATION_STG
     *
     * @mbggenerated Thu Jan 30 14:59:01 ICT 2014
     */
    int updateByExample(@Param("record") LocationUploadStage record, @Param("example") LocationUploadStageExample example);
}