package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.OrganizationContact;
import co.id.fifgroup.workstructure.domain.OrganizationContactExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrganizationContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int countByExample(OrganizationContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int deleteByExample(OrganizationContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int deleteByPrimaryKey(Long contactId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int insert(OrganizationContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int insertSelective(OrganizationContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    List<OrganizationContact> selectByExampleWithRowbounds(OrganizationContactExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    List<OrganizationContact> selectByExample(OrganizationContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    OrganizationContact selectByPrimaryKey(Long contactId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByExampleSelective(@Param("record") OrganizationContact record, @Param("example") OrganizationContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByExample(@Param("record") OrganizationContact record, @Param("example") OrganizationContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByPrimaryKeySelective(OrganizationContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_CONTACTS
     *
     * @mbggenerated Wed Apr 03 21:32:49 ICT 2013
     */
    int updateByPrimaryKey(OrganizationContact record);
}