package co.id.fifgroup.workstructure.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.workstructure.domain.OrganizationHierarchyUploadStage;
import co.id.fifgroup.workstructure.domain.OrganizationUploadStageExample;

public interface OrganizationHierarchyUploadStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_STG
     *
     * @mbggenerated Wed Jul 03 14:35:19 ICT 2013
     */
    int countByExample(OrganizationUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_STG
     *
     * @mbggenerated Wed Jul 03 14:35:19 ICT 2013
     */
    int deleteByExample(OrganizationUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_STG
     *
     * @mbggenerated Wed Jul 03 14:35:19 ICT 2013
     */
    int insert(OrganizationHierarchyUploadStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_STG
     *
     * @mbggenerated Wed Jul 03 14:35:19 ICT 2013
     */
    int insertSelective(OrganizationHierarchyUploadStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_STG
     *
     * @mbggenerated Wed Jul 03 14:35:19 ICT 2013
     */
    List<OrganizationHierarchyUploadStage> selectByExampleWithRowbounds(OrganizationUploadStageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_STG
     *
     * @mbggenerated Wed Jul 03 14:35:19 ICT 2013
     */
    List<OrganizationHierarchyUploadStage> selectByExample(OrganizationUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_STG
     *
     * @mbggenerated Wed Jul 03 14:35:19 ICT 2013
     */
    int updateByExampleSelective(@Param("record") OrganizationHierarchyUploadStage record, @Param("example") OrganizationUploadStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORGANIZATION_STG
     *
     * @mbggenerated Wed Jul 03 14:35:19 ICT 2013
     */
    int updateByExample(@Param("record") OrganizationHierarchyUploadStage record, @Param("example") OrganizationUploadStageExample example);
}