package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.OrgHierarchyVersion;
import co.id.fifgroup.workstructure.domain.OrgHierarchyVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrgHierarchyVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int countByExample(OrgHierarchyVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int deleteByExample(OrgHierarchyVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int deleteByPrimaryKey(Long versionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int insert(OrgHierarchyVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int insertSelective(OrgHierarchyVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    List<OrgHierarchyVersion> selectByExampleWithRowbounds(OrgHierarchyVersionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    List<OrgHierarchyVersion> selectByExample(OrgHierarchyVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    OrgHierarchyVersion selectByPrimaryKey(Long versionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByExampleSelective(@Param("record") OrgHierarchyVersion record, @Param("example") OrgHierarchyVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByExample(@Param("record") OrgHierarchyVersion record, @Param("example") OrgHierarchyVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByPrimaryKeySelective(OrgHierarchyVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByPrimaryKey(OrgHierarchyVersion record);
}