package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.OrgLevelHierElement;
import co.id.fifgroup.workstructure.domain.OrgLevelHierElementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrgLevelHierElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int countByExample(OrgLevelHierElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int deleteByExample(OrgLevelHierElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int deleteByPrimaryKey(Long elementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int insert(OrgLevelHierElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int insertSelective(OrgLevelHierElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    List<OrgLevelHierElement> selectByExampleWithRowbounds(OrgLevelHierElementExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    List<OrgLevelHierElement> selectByExample(OrgLevelHierElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    OrgLevelHierElement selectByPrimaryKey(Long elementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByExampleSelective(@Param("record") OrgLevelHierElement record, @Param("example") OrgLevelHierElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByExample(@Param("record") OrgLevelHierElement record, @Param("example") OrgLevelHierElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByPrimaryKeySelective(OrgLevelHierElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_ELEMENTS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByPrimaryKey(OrgLevelHierElement record);
}