package co.id.fifgroup.workstructure.dao;

import co.id.fifgroup.workstructure.domain.OrgLevelHierVersion;
import co.id.fifgroup.workstructure.domain.OrgLevelHierVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrgLevelHierVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int countByExample(OrgLevelHierVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int deleteByPrimaryKey(Long versionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int insert(OrgLevelHierVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int insertSelective(OrgLevelHierVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    List<OrgLevelHierVersion> selectByExampleWithRowbounds(OrgLevelHierVersionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    List<OrgLevelHierVersion> selectByExample(OrgLevelHierVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    OrgLevelHierVersion selectByPrimaryKey(Long versionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByExampleSelective(@Param("record") OrgLevelHierVersion record, @Param("example") OrgLevelHierVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByExample(@Param("record") OrgLevelHierVersion record, @Param("example") OrgLevelHierVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByPrimaryKeySelective(OrgLevelHierVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WOS_ORG_LEVEL_HIER_VERSIONS
     *
     * @mbggenerated Wed Apr 03 21:32:50 ICT 2013
     */
    int updateByPrimaryKey(OrgLevelHierVersion record);
}