package co.id.fifgroup.basicsetup.dao;

import co.id.fifgroup.basicsetup.domain.BusinessGroup;
import co.id.fifgroup.basicsetup.domain.BusinessGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BusinessGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int countByExample(BusinessGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int deleteByExample(BusinessGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int deleteByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int insert(BusinessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int insertSelective(BusinessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    List<BusinessGroup> selectByExampleWithRowbounds(BusinessGroupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    List<BusinessGroup> selectByExample(BusinessGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    BusinessGroup selectByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int updateByExampleSelective(@Param("record") BusinessGroup record, @Param("example") BusinessGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int updateByExample(@Param("record") BusinessGroup record, @Param("example") BusinessGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int updateByPrimaryKeySelective(BusinessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_BUSINESS_GROUPS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int updateByPrimaryKey(BusinessGroup record);
}