package co.id.fifgroup.basicsetup.dao;

import co.id.fifgroup.basicsetup.domain.Company;
import co.id.fifgroup.basicsetup.domain.CompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    int countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    int deleteByPrimaryKey(Long companySeqNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    List<Company> selectByExampleWithRowbounds(CompanyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    Company selectByPrimaryKey(Long companySeqNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    int updateByExampleSelective(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    int updateByExample(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_COMPANIES
     *
     * @mbggenerated Thu Mar 28 20:13:05 ICT 2013
     */
    int updateByPrimaryKey(Company record);
}