package co.id.fifgroup.basicsetup.dao;

import co.id.fifgroup.basicsetup.domain.FormulaUsage;
import co.id.fifgroup.basicsetup.domain.FormulaUsageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FormulaUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    int countByExample(FormulaUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    int deleteByExample(FormulaUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    int deleteByPrimaryKey(Long formulaUsageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    int insert(FormulaUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    int insertSelective(FormulaUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    List<FormulaUsage> selectByExampleWithRowbounds(FormulaUsageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    List<FormulaUsage> selectByExample(FormulaUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    FormulaUsage selectByPrimaryKey(Long formulaUsageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    int updateByExampleSelective(@Param("record") FormulaUsage record, @Param("example") FormulaUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    int updateByExample(@Param("record") FormulaUsage record, @Param("example") FormulaUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    int updateByPrimaryKeySelective(FormulaUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_USAGES
     *
     * @mbggenerated Tue Apr 02 18:10:20 ICT 2013
     */
    int updateByPrimaryKey(FormulaUsage record);
}