package co.id.fifgroup.basicsetup.dao;

import co.id.fifgroup.basicsetup.domain.Formula;
import co.id.fifgroup.basicsetup.domain.FormulaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FormulaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    int countByExample(FormulaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    int deleteByExample(FormulaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    int insert(Formula record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    int insertSelective(Formula record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    List<Formula> selectByExampleWithRowbounds(FormulaExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    List<Formula> selectByExample(FormulaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    Formula selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    int updateByExampleSelective(@Param("record") Formula record, @Param("example") FormulaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    int updateByExample(@Param("record") Formula record, @Param("example") FormulaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    int updateByPrimaryKeySelective(Formula record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA
     *
     * @mbggenerated Tue Mar 26 16:09:54 ICT 2013
     */
    int updateByPrimaryKey(Formula record);
}