package co.id.fifgroup.basicsetup.dao;

import co.id.fifgroup.basicsetup.domain.FormulaVersionParam;
import co.id.fifgroup.basicsetup.domain.FormulaVersionParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FormulaVersionParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    int countByExample(FormulaVersionParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    int deleteByExample(FormulaVersionParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    int deleteByPrimaryKey(@Param("versionId") Long versionId, @Param("formulaParameterId") Long formulaParameterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    int insert(FormulaVersionParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    int insertSelective(FormulaVersionParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    List<FormulaVersionParam> selectByExampleWithRowbounds(FormulaVersionParamExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    List<FormulaVersionParam> selectByExample(FormulaVersionParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    FormulaVersionParam selectByPrimaryKey(@Param("versionId") Long versionId, @Param("formulaParameterId") Long formulaParameterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    int updateByExampleSelective(@Param("record") FormulaVersionParam record, @Param("example") FormulaVersionParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    int updateByExample(@Param("record") FormulaVersionParam record, @Param("example") FormulaVersionParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    int updateByPrimaryKeySelective(FormulaVersionParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_FORMULA_VERSION_PARAMS
     *
     * @mbggenerated Mon Apr 01 14:45:08 ICT 2013
     */
    int updateByPrimaryKey(FormulaVersionParam record);
}