package co.id.fifgroup.basicsetup.dao;

import co.id.fifgroup.basicsetup.domain.Module;
import co.id.fifgroup.basicsetup.domain.ModuleExample;
import co.id.fifgroup.basicsetup.dto.ModuleDTO;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    int countByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    int deleteByPrimaryKey(Long moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    List<Module> selectByExampleWithRowbounds(ModuleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    List<Module> selectByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    Module selectByPrimaryKey(Long moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    int updateByExampleSelective(@Param("record") Module record, @Param("example") ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    int updateByExample(@Param("record") Module record, @Param("example") ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_MODULES
     *
     * @mbggenerated Wed Mar 13 19:09:01 ICT 2013
     */
    int updateByPrimaryKey(Module record);
}