package co.id.fifgroup.basicsetup.dao;

import co.id.fifgroup.basicsetup.domain.Printer;
import co.id.fifgroup.basicsetup.domain.PrinterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PrinterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int countByExample(PrinterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int deleteByPrimaryKey(Long printerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int insert(Printer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int insertSelective(Printer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    List<Printer> selectByExampleWithRowbounds(PrinterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    List<Printer> selectByExample(PrinterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    Printer selectByPrimaryKey(Long printerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int updateByExampleSelective(@Param("record") Printer record, @Param("example") PrinterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int updateByExample(@Param("record") Printer record, @Param("example") PrinterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int updateByPrimaryKeySelective(Printer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_PRINTERS
     *
     * @mbggenerated Wed Mar 20 11:18:05 ICT 2013
     */
    int updateByPrimaryKey(Printer record);
}