package co.id.fifgroup.basicsetup.dao;

import co.id.fifgroup.basicsetup.domain.TransactionType;
import co.id.fifgroup.basicsetup.domain.TransactionTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TransactionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    int countByExample(TransactionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    int deleteByPrimaryKey(Long trxTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    int insert(TransactionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    int insertSelective(TransactionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    List<TransactionType> selectByExampleWithRowbounds(TransactionTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    List<TransactionType> selectByExample(TransactionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    TransactionType selectByPrimaryKey(Long trxTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    int updateByExampleSelective(@Param("record") TransactionType record, @Param("example") TransactionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    int updateByExample(@Param("record") TransactionType record, @Param("example") TransactionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    int updateByPrimaryKeySelective(TransactionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSE_TRANSACTION_TYPES
     *
     * @mbggenerated Wed Mar 20 17:10:50 ICT 2013
     */
    int updateByPrimaryKey(TransactionType record);
}