package co.id.fifgroup.personneladmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.personneladmin.domain.AccountInfoStage;
import co.id.fifgroup.personneladmin.domain.AccountInfoStageExample;

public interface AccountInfoStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ACCOUNT_INFO_STG
     *
     * @mbggenerated Wed Jul 03 19:55:52 ICT 2013
     */
    int countByExample(AccountInfoStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ACCOUNT_INFO_STG
     *
     * @mbggenerated Wed Jul 03 19:55:52 ICT 2013
     */
    int deleteByExample(AccountInfoStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ACCOUNT_INFO_STG
     *
     * @mbggenerated Wed Jul 03 19:55:52 ICT 2013
     */
    int insert(AccountInfoStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ACCOUNT_INFO_STG
     *
     * @mbggenerated Wed Jul 03 19:55:52 ICT 2013
     */
    int insertSelective(AccountInfoStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ACCOUNT_INFO_STG
     *
     * @mbggenerated Wed Jul 03 19:55:52 ICT 2013
     */
    List<AccountInfoStage> selectByExampleWithRowbounds(AccountInfoStageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ACCOUNT_INFO_STG
     *
     * @mbggenerated Wed Jul 03 19:55:52 ICT 2013
     */
    List<AccountInfoStage> selectByExample(AccountInfoStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ACCOUNT_INFO_STG
     *
     * @mbggenerated Wed Jul 03 19:55:52 ICT 2013
     */
    int updateByExampleSelective(@Param("record") AccountInfoStage record, @Param("example") AccountInfoStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ACCOUNT_INFO_STG
     *
     * @mbggenerated Wed Jul 03 19:55:52 ICT 2013
     */
    int updateByExample(@Param("record") AccountInfoStage record, @Param("example") AccountInfoStageExample example);
}