package co.id.fifgroup.personneladmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.personneladmin.domain.Apparel;
import co.id.fifgroup.personneladmin.domain.ApparelExample;

public interface ApparelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int countByExample(ApparelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int deleteByExample(ApparelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int deleteByPrimaryKey(Long apparelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int insert(Apparel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int insertSelective(Apparel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    List<Apparel> selectByExampleWithRowbounds(ApparelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    List<Apparel> selectByExample(ApparelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    Apparel selectByPrimaryKey(Long apparelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int updateByExampleSelective(@Param("record") Apparel record, @Param("example") ApparelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int updateByExample(@Param("record") Apparel record, @Param("example") ApparelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int updateByPrimaryKeySelective(Apparel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_APPARELS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int updateByPrimaryKey(Apparel record);
}