package co.id.fifgroup.personneladmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.personneladmin.domain.AssignmentOtherInfo;
import co.id.fifgroup.personneladmin.domain.AssignmentOtherInfoExample;

public interface AssignmentOtherInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    int countByExample(AssignmentOtherInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    int deleteByExample(AssignmentOtherInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    int deleteByPrimaryKey(@Param("otherInfoDtlId") Long otherInfoDtlId, @Param("assignmentId") Long assignmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    int insert(AssignmentOtherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    int insertSelective(AssignmentOtherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    List<AssignmentOtherInfo> selectByExampleWithRowbounds(AssignmentOtherInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    List<AssignmentOtherInfo> selectByExample(AssignmentOtherInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    AssignmentOtherInfo selectByPrimaryKey(@Param("otherInfoDtlId") Long otherInfoDtlId, @Param("assignmentId") Long assignmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    int updateByExampleSelective(@Param("record") AssignmentOtherInfo record, @Param("example") AssignmentOtherInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    int updateByExample(@Param("record") AssignmentOtherInfo record, @Param("example") AssignmentOtherInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    int updateByPrimaryKeySelective(AssignmentOtherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_ASSIGNMENT_OTHER_INFO
     *
     * @mbggenerated Tue May 28 15:42:23 ICT 2013
     */
    int updateByPrimaryKey(AssignmentOtherInfo record);
}