package co.id.fifgroup.personneladmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.personneladmin.domain.JobQuestionSet;
import co.id.fifgroup.personneladmin.domain.JobQuestionSetExample;

public interface JobQuestionSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    int countByExample(JobQuestionSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    int deleteByExample(JobQuestionSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    int deleteByPrimaryKey(Long jobQuestionSetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    int insert(JobQuestionSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    int insertSelective(JobQuestionSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    List<JobQuestionSet> selectByExampleWithRowbounds(JobQuestionSetExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    List<JobQuestionSet> selectByExample(JobQuestionSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    JobQuestionSet selectByPrimaryKey(Long jobQuestionSetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    int updateByExampleSelective(@Param("record") JobQuestionSet record, @Param("example") JobQuestionSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    int updateByExample(@Param("record") JobQuestionSet record, @Param("example") JobQuestionSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    int updateByPrimaryKeySelective(JobQuestionSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_JOB_QUESTION_SETS
     *
     * @mbggenerated Tue Jun 18 18:38:31 ICT 2013
     */
    int updateByPrimaryKey(JobQuestionSet record);
}