package co.id.fifgroup.personneladmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.personneladmin.domain.MobilityEmployee;
import co.id.fifgroup.personneladmin.domain.MobilityEmployeeExample;

public interface MobilityEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    int countByExample(MobilityEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    int deleteByExample(MobilityEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    int deleteByPrimaryKey(Long mobilityEmployeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    int insert(MobilityEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    int insertSelective(MobilityEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    List<MobilityEmployee> selectByExampleWithRowbounds(MobilityEmployeeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    List<MobilityEmployee> selectByExample(MobilityEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    MobilityEmployee selectByPrimaryKey(Long mobilityEmployeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    int updateByExampleSelective(@Param("record") MobilityEmployee record, @Param("example") MobilityEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    int updateByExample(@Param("record") MobilityEmployee record, @Param("example") MobilityEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    int updateByPrimaryKeySelective(MobilityEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_MOBILITY_EMPLOYEES
     *
     * @mbggenerated Tue Feb 10 17:19:52 ICT 2015
     */
    int updateByPrimaryKey(MobilityEmployee record);
}