package co.id.fifgroup.personneladmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.personneladmin.domain.PersonalInformation;
import co.id.fifgroup.personneladmin.domain.PersonalInformationExample;

public interface PersonalInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    int countByExample(PersonalInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    int deleteByExample(PersonalInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    int deleteByPrimaryKey(Long informationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    int insert(PersonalInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    int insertSelective(PersonalInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    List<PersonalInformation> selectByExampleWithRowbounds(PersonalInformationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    List<PersonalInformation> selectByExample(PersonalInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    PersonalInformation selectByPrimaryKey(Long informationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    int updateByExampleSelective(@Param("record") PersonalInformation record, @Param("example") PersonalInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    int updateByExample(@Param("record") PersonalInformation record, @Param("example") PersonalInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    int updateByPrimaryKeySelective(PersonalInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_PERSONAL_INFORMATIONS
     *
     * @mbggenerated Thu Sep 19 18:47:54 ICT 2013
     */
    int updateByPrimaryKey(PersonalInformation record);
}