package co.id.fifgroup.personneladmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.personneladmin.domain.ProbationCompetencyReview;
import co.id.fifgroup.personneladmin.domain.ProbationCompetencyReviewExample;

public interface ProbationCompetencyReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    int countByExample(ProbationCompetencyReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    int deleteByExample(ProbationCompetencyReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    int deleteByPrimaryKey(Long competencyReviewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    int insert(ProbationCompetencyReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    int insertSelective(ProbationCompetencyReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    List<ProbationCompetencyReview> selectByExampleWithRowbounds(ProbationCompetencyReviewExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    List<ProbationCompetencyReview> selectByExample(ProbationCompetencyReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    ProbationCompetencyReview selectByPrimaryKey(Long competencyReviewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    int updateByExampleSelective(@Param("record") ProbationCompetencyReview record, @Param("example") ProbationCompetencyReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    int updateByExample(@Param("record") ProbationCompetencyReview record, @Param("example") ProbationCompetencyReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    int updateByPrimaryKeySelective(ProbationCompetencyReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_COMPETENCY_REVIEWS
     *
     * @mbggenerated Fri Feb 20 21:01:27 ICT 2015
     */
    int updateByPrimaryKey(ProbationCompetencyReview record);
}