package co.id.fifgroup.personneladmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.personneladmin.domain.SecondaryAssignment;
import co.id.fifgroup.personneladmin.domain.SecondaryAssignmentExample;

public interface SecondaryAssignmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    int countByExample(SecondaryAssignmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    int deleteByExample(SecondaryAssignmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    int deleteByPrimaryKey(Long assignmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    int insert(SecondaryAssignment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    int insertSelective(SecondaryAssignment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    List<SecondaryAssignment> selectByExampleWithRowbounds(SecondaryAssignmentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    List<SecondaryAssignment> selectByExample(SecondaryAssignmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    SecondaryAssignment selectByPrimaryKey(Long assignmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    int updateByExampleSelective(@Param("record") SecondaryAssignment record, @Param("example") SecondaryAssignmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    int updateByExample(@Param("record") SecondaryAssignment record, @Param("example") SecondaryAssignmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    int updateByPrimaryKeySelective(SecondaryAssignment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_SECONDARY_ASSIGNMENTS
     *
     * @mbggenerated Tue May 28 17:01:01 ICT 2013
     */
    int updateByPrimaryKey(SecondaryAssignment record);
}