package co.id.fifgroup.personneladmin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import co.id.fifgroup.personneladmin.domain.VitalStatistic;
import co.id.fifgroup.personneladmin.domain.VitalStatisticExample;

public interface VitalStatisticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int countByExample(VitalStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int deleteByExample(VitalStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int deleteByPrimaryKey(Long vitalStatisticId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int insert(VitalStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int insertSelective(VitalStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    List<VitalStatistic> selectByExampleWithRowbounds(VitalStatisticExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    List<VitalStatistic> selectByExample(VitalStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    VitalStatistic selectByPrimaryKey(Long vitalStatisticId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int updateByExampleSelective(@Param("record") VitalStatistic record, @Param("example") VitalStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int updateByExample(@Param("record") VitalStatistic record, @Param("example") VitalStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int updateByPrimaryKeySelective(VitalStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PEA_VITAL_STATISTICS
     *
     * @mbggenerated Mon Jun 03 20:18:16 ICT 2013
     */
    int updateByPrimaryKey(VitalStatistic record);
}